### ISSUE TITLE
Taskboard for status of S6 / basic gameplay features to be implemented

### ISSUE THREAD

**Issue by nitoygo** [MUnique/OpenMU#119]
I noticed [Progress.md](https://github.com/MUnique/OpenMU/blob/master/doc/Progress.md) shows the list of implemented and ongoing features.

I'd like to confirm if this md page is always updated... (Or sync"d with the feature branches).

I think it would be better (for tracking purposes) if there a taskboard similar to [Version 0.97d Support
 Taskboard](https://github.com/MUnique/OpenMU/projects/1) for those planning to help out. Then assign the feature branch to the specific task unit.

I'd like to help too but I'm still studying the source code (AND C# >.<).
Now, I can only do some tests in-game. (but it's random since I don't know which are working/implemented or not...)

Thanks!

**Comment by sven-n** [comment]
Yes I think it’s currently in sync because I didn’t add game features for a while.
I’ll try to add a project board when I get time.

**Comment by sven-n** [comment]
I think I have it now - just lacking some details, ofc
