### ISSUE TITLE
Trade issues

### ISSUE THREAD

**Issue by nitoygo** [MUnique/OpenMU#121]
I'll just note things I detected here for now (I've posted other things as separate issues)

For trade, I noticed the following:
- Trading causes items in inventory to be re-arranged (when cancelled?)
- Equipped armor parts moves down in the inventory space
- Some of these unwanted placement of items causes conflicts on next login (items being saved on the same index in inventory)

There may be more but I can't check the test character anymore since I can't log them in properly without fixing their conflicting item location (in the inventory) first in postgresql / or deleting all items.

**Comment by sven-n** [comment]
Hey, I found this issue, too. I’ll fix it soon.

**Comment by nitoygo** [comment]
Sorry! wrong issue closed.
I am commenting on the other issue about excellent item pick up.
