### ISSUE TITLE
Dockerizing the Project

### ISSUE THREAD

**Issue by fenos** [MUnique/OpenMU#126]
I'm Opening this issue to track the progress on dockerizing the project!
Think how cool would be running the server doing 

```
docker run -d \
-p 55901:55901 55902:55902 55903:55903 44405:44405 55980:55980 \
-e DB_DSN="postgres://localhost:5432/user@password/db" \
openmu/openmu:latest
```

### Benefits:
- Immutable deployments that works all the time
- Portability - Runs on clouds, local, windows, mac, linux in the same way
- Scalability, scale the server to multiple instances behind a loadbalancer with 1 command
- Easy customisation!

I'd love to contribute to this! 

I've never run a C# application before, but i'm glad to learn about it since i'm willing to contribute to the project going further.

I'm a golang developer btw 😄

**Comment by sven-n** [comment]
Hey, I think that would be great, too. It would be a start to have a simple way to install the server and its dependencies. Scaling with a something like a load balancer isn’t so easy and probably not required.

Currently, the database connection strings are set up in a configuration file. I’m no docker expert, but I think for docker it needs to be changed to use environment variables.

**Comment by xujintao** [comment]
Dockerizing openmu would be amazing.
However, scalability seems like unrealistic, as the game server usually use cache(vector, list, map) locally instead of redis etc. for better performance, which makes server be stateful, and server with state can not scale.

**Comment by fenos** [comment]
@sven-n Hi, I'm getting a problem while compiling the app in the Docker container, there is no error trace and I'm not sure what's going on. Can you help, please

It exits the build process after this log:

```
  Bundler: Begin processing bundleconfig.json
        Bundled wwwroot/content/css/app.css
        Minified wwwroot/content/css/app.min.css
  Bundler: Done processing bundleconfig.json
  MUnique.OpenMU.AdminPanel -> /app/bin/Debug/MUnique.OpenMU.AdminPanel.dll
  MUnique.OpenMU.AdminPanel -> /app/bin/Debug/MUnique.OpenMU.AdminPanel.Views.dll
  MUnique.OpenMU.AdminPanel -> /app/src/AdminPanel/out/
The command '/bin/sh -c dotnet publish src/MUnique.OpenMU.sln -o out' returned a non-zero code: 1
```

How to reproduce:

- Install docker
- create a file called `Dockerfile` in the root of the project

paste this:

```
FROM mcr.microsoft.com/dotnet/core/sdk:2.1 AS build

RUN apt-get update && apt-get install curl -y
RUN curl -sL https://deb.nodesource.com/setup_10.x | bash -
RUN apt-get install nodejs npm && npm i -g typescript
RUN mkdir app

COPY src/ ./app/src
COPY tests/ ./app/tests
COPY doc/ ./app/doc

WORKDIR /app
RUN dotnet restore src/MUnique.OpenMU.sln
RUN dotnet publish src/MUnique.OpenMU.sln -o out

FROM mcr.microsoft.com/dotnet/core/aspnet:2.1 AS runtime
EXPOSE 1234
EXPOSE 55901
EXPOSE 55902
EXPOSE 55903
EXPOSE 44405
EXPOSE 55980
WORKDIR /app/
COPY --from=build /app/out ./
ENTRYPOINT ["dotnet", "MUnique.OpenMU.dll"]
```

run `docker build -t OpenMu -f Dockerfile .`

**Comment by sven-n** [comment]
Nice, thanks. Can you try it with parameter ```-v d``` at the publish command? It should output more information about the error.

**Comment by fenos** [comment]
@sven-n ok, this is the stack trace:

```
  MUnique.OpenMU.AdminPanel -> /app/src/AdminPanel/out/
       Done executing task "Message".
  15:7>Done building target "Publish" in project "MUnique.OpenMU.AdminPanel.csproj".
       Target "_InitProjectCapabilityProperties" skipped. Previously built successfully.
  15:7>Target "_InitPublishIntermediateOutputPath" in file "/usr/share/dotnet/sdk/2.1.700/Sdks/Microsoft.NET.Sdk.Publish/build/netstandard1.0/DotNetCLIToolTargets/Microsoft.NET.Sdk.DotNetCLITool.targets" from project "/app/src/AdminPanel/MUnique.OpenMU.AdminPanel.csproj" (target "_AspNetCoreProjectSystemPostPublish" depends on it):
       Task "ConvertToAbsolutePath"
       Done executing task "ConvertToAbsolutePath".
  15:7>Done building target "_InitPublishIntermediateOutputPath" in project "MUnique.OpenMU.AdminPanel.csproj".
  15:7>Target "_TransformWebConfig" in file "/usr/share/dotnet/sdk/2.1.700/Sdks/Microsoft.NET.Sdk.Publish/build/netstandard1.0/TransformTargets/Microsoft.NET.Sdk.Publish.TransformFiles.targets" from project "/app/src/AdminPanel/MUnique.OpenMU.AdminPanel.csproj" (target "_AspNetCoreProjectSystemPostPublish" depends on it):
       Using "TransformWebConfig" task from assembly "/usr/share/dotnet/sdk/2.1.700/Sdks/Microsoft.NET.Sdk.Publish/build/netstandard1.0/../../tools/netcoreapp1.0/Microsoft.NET.Sdk.Publish.Tasks.dll".
       Task "TransformWebConfig"
         Configuring the following project for use with IIS: '/app/src/AdminPanel/out/'
         No web.config found. Creating '/app/src/AdminPanel/out/web.config'
         Configuring project completed successfully
```

Any advise?

**Comment by fenos** [comment]
It looks like the `MSBuild` fails can you tell why?

**Comment by sven-n** [comment]
I don't know, but I think publishing the whole solution is wrong here. To start the server, we just need the startup project.

Try this:
```
FROM mcr.microsoft.com/dotnet/core/sdk:2.1 AS build

RUN apt-get update && apt-get install curl -y
RUN curl -sL https://deb.nodesource.com/setup_10.x | bash -
RUN apt-get install nodejs npm && npm i -g typescript
RUN mkdir app

COPY src/ ./app/src
COPY tests/ ./app/tests
COPY doc/ ./app/doc

WORKDIR /app
RUN dotnet restore src/MUnique.OpenMU.sln
RUN dotnet publish src/Startup/MUnique.OpenMU.Startup.csproj -o out

FROM mcr.microsoft.com/dotnet/core/aspnet:2.1 AS runtime
EXPOSE 1234
EXPOSE 55901
EXPOSE 55902
EXPOSE 55903
EXPOSE 44405
EXPOSE 55980
WORKDIR /app/
COPY --from=build /app/src/Startup/out ./
ENTRYPOINT ["dotnet", "MUnique.OpenMU.Startup.dll", "-demo"]
```

I added the demo parameter, so it should start without postgres for now. I couldn't test this further as my HDD got filled up by it xD

**Comment by fenos** [comment]
@sven-n Amazing!! It built successfully!!

Now when i start the container with: 

```
docker run -p 1234:1234 -p 44405 -p 55901 -p 55902 -p 55903 fenos/mu:latest
````

I get 

```
[INFO ]MUnique.OpenMU.Startup.Program] [(null)] - Start initializing sub-components
[INFO ][MUnique.OpenMU.Startup.Program] [(null)] - Start initializing game servers
[INFO ][MUnique.OpenMU.Startup.Program] [0] - Game Server 0 - [Server 0] initialized
[INFO ]MUnique.OpenMU.Startup.Program] [1] - Game Server 1 - [Server 1] initialized
[INFO ][MUnique.OpenMU.Startup.Program] [2] - Game Server 2 - [Server 2] initialized
[INFO ][MUnique.OpenMU.Startup.Program] [(null)] - All game servers initialized, elapsed time: 00:00:00.1345274
[INFO ][MUnique.OpenMU.Startup.Program] [(null)] - Start initializing admin panel

Unknown command
Unknown command
Unknown command
Unknown command
Unknown command
Unknown command
Unknown command
Unknown command
Unknown command
Unknown command
Unknown command
Unknown command
Unknown command
Unknown command
Unknown command
Unknown command
Unknown command

... goes on infinitely
```

Once this starts we are really at a good point, plugging Postgres should be relatively easy!

**Comment by sven-n** [comment]
Pushed a fix for that.

I had issues with some missing js files in the Admin Panel. I got it running with this Dockerfile:
```
FROM mcr.microsoft.com/dotnet/core/sdk:2.1 AS build

RUN apt-get update && apt-get install curl -y
RUN curl -sL https://deb.nodesource.com/setup_10.x | bash -
RUN apt-get install nodejs npm && npm i -g typescript
RUN mkdir app

COPY src/ ./app/src
COPY tests/ ./app/tests
COPY doc/ ./app/doc

WORKDIR /app
RUN dotnet restore src/MUnique.OpenMU.sln
RUN dotnet publish src/Startup/MUnique.OpenMU.Startup.csproj -o out

FROM mcr.microsoft.com/dotnet/core/aspnet:2.1 AS runtime
EXPOSE 1234
EXPOSE 55901
EXPOSE 55902
EXPOSE 55903
EXPOSE 44405
EXPOSE 55980
WORKDIR /app/
COPY --from=build /app/src/Startup/out ./
COPY --from=build /app/bin/Debug/wwwroot/content/js ./wwwroot/content/js
ENTRYPOINT ["dotnet", "MUnique.OpenMU.Startup.dll", "-demo"]
```

**Comment by fenos** [comment]
@sven-n yes the container started successfully here is the log:

```
[INFO ][MUnique.OpenMU.Startup.Program] [(null)] - Start initializing sub-components
[INFO ][MUnique.OpenMU.Startup.Program] [(null)] - Start initializing game servers
[INFO ][MUnique.OpenMU.Startup.Program] [0] - Game Server 0 - [Server 0] initialized
[INFO ][MUnique.OpenMU.Startup.Program] [1] - Game Server 1 - [Server 1] initialized
[INFO ][MUnique.OpenMU.Startup.Program] [2] - Game Server 2 - [Server 2] initialized
[INFO ][MUnique.OpenMU.Startup.Program] [(null)] - All game servers initialized, elapsed time: 00:00:00.1504707
[INFO ][MUnique.OpenMU.Startup.Program] [(null)] - Start initializing admin panel
[INFO ][MUnique.OpenMU.Startup.Program] [(null)] - Admin panel initialized
```

However when i visit: http://localhost:1234/admin

it get in the browser console:

```
Uncaught ReferenceError: System is not defined
    at app.js:25
admin:17 Uncaught ReferenceError: System is not defined
    at admin:17
admin:35 Uncaught ReferenceError: System is not defined
    at admin:35
```

```
// System is not defined
System.register("stores/accounts/types", [], function (exports_1, context_1) {
    "use strict";
```

**Comment by fenos** [comment]
@sven-n ignore I made it work, now I'll play around a bit.

can you email me a MuClient you used to test the server please:

fabri.feno@gmail.com

**Comment by sven-n** [comment]
http://forum.ragezone.com/f197/release-client-1-04d-eng-1143697/

**Comment by fenos** [comment]
@sven-n Thanks again for your help getting slightly further.

Although I can't connect to the game. The client is giving me the error "You Disconnected from the Server".

I've edited the `main.exe` and changed the IP address to point to my local server.
Do you know any way to debug this? Example ping game server etc?

I'm able to connect to the admin panel though

**Comment by sven-n** [comment]
No problem, you’re welcome :)
Debugging this is a bit hard I think. Which kind of IP did you insert into the main.exe? If you inserted 127.0.0.1, it wouldn’t work. I don’t have much knowledge about networking with docker, but maybe you could try to find out with ```netstat``` if all listening ports are available.

**Comment by fenos** [comment]
I'm using docker IP to access to the admin panel, for me: `192.168.0.21:1234/admin`
I used the same IP editing the main:

<img width="319" alt="Screenshot 2019-07-08 at 19 36 45" src="https://user-images.githubusercontent.com/4754064/60834118-d2d87900-a1b7-11e9-825a-a1d2b08e7ef5.png">

**Comment by fenos** [comment]
I'm suspecting this line: https://github.com/MUnique/OpenMU/blob/46abbcb3616aca22f6cbb927de6de49ff9136062/src/GameServer/DefaultTcpGameServerListener.cs#L71

Since from the logs i can see the following:

```
[INFO ] 2019-07-08 18:23:58,586 [MUnique.OpenMU.ConnectServer.ConnectServer] [1] - GameServer 1 - [Server 1] is registering with endpoint 80.1.148.29:55902
[INFO ] 2019-07-08 18:23:58,591 [MUnique.OpenMU.ConnectServer.ConnectServer] [1] - GameServer 1 - [Server 1] has registered with endpoint 80.1.148.29:55902
```

The server gets bound to this `IP` 80.1.148.29 - which i'm not sure what ip it is at the moment.

Although is there a way to specify a custom IP?

**Comment by sven-n** [comment]
Actually the tcp listeners are bound to 0.0.0.0.
The game servers are registering at the connect server with their public ip, by default. To change this behavior, there is a start parameter ```-local``` with which it selects an address of a local network interface. It may help in your case ;)

**Comment by fenos** [comment]
@sven-n thanks! Another question, which one should be the port to be exposed? and which one is UDP?

**Comment by sven-n** [comment]
1234 (admin panel)
55901, 55902, 55903 (game servers)
44405 (connect server)
55980 (chat server)

All TCP, no UDP ;)

**Comment by fenos** [comment]
@sven-n Cool! Solved one more piece! 

Now I can see the list of servers, I click on it and it crashes saying `You Disconnected from the Server`

Still investigating... welcomes ideas

**Comment by sven-n** [comment]
okay, then the connection to the game server is not getting established. Either because the ports 5590x are blocked, or because the connect server reports an unreachable IP address back to the game client (that’s the same one which the game server is registering according to the log)

**Comment by fenos** [comment]
Mmmh, ok I've done a bit of digging.

I found a way to ping 55902 to exclude the fact that the port is blocked:

```
psping 192.168.0.21:55902
TCP connect to 192.168.0.21:55902:
5 iterations (warmup 1) ping test:
Connecting to 192.168.0.21:55902 (warmup): from 192.168.115.224:50315: 2.17ms
Connecting to 192.168.0.21:55902: from 192.168.115.224:50316: 1.24ms
Connecting to 192.168.0.21:55902: from 192.168.115.224:50317: 1.31ms
Connecting to 192.168.0.21:55902: from 192.168.115.224:50318: 1.29ms
Connecting to 192.168.0.21:55902: from 192.168.115.224:50319: 1.35ms

TCP connect statistics for 192.168.0.21:55902:
  Sent = 4, Received = 4, Lost = 0 (0% loss),
  Minimum = 1.24ms, Maximum = 1.35ms, Average = 1.30ms
```

Packets are received ok!

Next, I tried a bunch of IP addresses but i've still got the same issue of clicking the server and getting disconnected.

If the connect server uses the local ip i'm seeing used in the log, to try and connect to the game serer is should work. 

If instead, it uses the public client IP that i set in the `main.exe` than the connect server cannot reach that IP from within docker it has to use the one in the logs

**Comment by fenos** [comment]
I had no luck for today to login into the game

**Comment by fenos** [comment]
Another thing I've noticed is that any the logs from the method `BeginAccept` doesn't show during bootstrap. 

https://github.com/MUnique/OpenMU/blob/46abbcb3616aca22f6cbb927de6de49ff9136062/src/GameServer/DefaultTcpGameServerListener.cs#L95

It goes directly to:
https://github.com/MUnique/OpenMU/blob/46abbcb3616aca22f6cbb927de6de49ff9136062/src/GameServer/DefaultTcpGameServerListener.cs#L73

**Comment by sven-n** [comment]
It runs async, so this could be normal ;)
I managed to enter the map after some additional adjustments to the code. I still don't have an idea what could be wrong in your case :-/

**Comment by fenos** [comment]
@sven-n Amazing! did you access the map from within the docker container? Can you share the adjustments in the code, please.

I just published it in the cloud (Digital Ocean) to test in a very clean and isolated environment (still with docker) and tried to connect to the game, but the same issue occurred. "You are Disconnected from the server" once I click on the server name

**Comment by sven-n** [comment]
I pushed all changes to master.
About my setup: I run Docker Desktop on Windows, the default linux docker container and started the game client on the same Windows host.

That's how I created and started the container:
```
To build the image:
  docker build -t openmudemo -f Dockerfile .

To run the image in a new container, named 'test':
  docker run --name test -d -p 1234:1234 -p 44405:44405 -p 55901:55901 openmudemo
```

Don't have slack right now and I'm mostly online on my phone ;-)

**Comment by fenos** [comment]
Ok, what mode (`local` or `public`) did you used on the docker image? what IP are you using from the client?

can you tell me what kind of connection is trying to make to the game server which fails and disconnects me?

**Comment by sven-n** [comment]
I use public mode, and I have no problem reaching my system with this IP. 
I launch my game client with 127.127.127.127:44405 but this should not make much difference. When clicking at a server, the connect server tells the game client to which IP and Port it should connect. In my case it returns the public ip and port 55901 for the first game server - and it works. In your case, this connection fails for some reason.

**Comment by fenos** [comment]
@sven-n could you try to connect to this server ip: 178.62.51.245 it's the server test running in docker I pushed in the cloud, it's still giving me this problem, I was wondering if it's something to do with my network or related to my machine

**Comment by sven-n** [comment]
It's strange. The first time I connected to your connect server and clicked on a game server, I got disconnected.
Then I tried again at server 1 and ended up on my docker container instance.
Directly launching the client to your ip and port 55901 works, btw! :)


Maybe there is an issue with the connect server response. When I experimented with 0.75 recently, I had some strange behavior as well.

**Comment by fenos** [comment]
@sven-n how can I lunch the client directly at port 55901?

**Comment by sven-n** [comment]
With this client launcher here: https://github.com/MUnique/OpenMU/tree/master/src/ClientLauncher

**Comment by fenos** [comment]
@sven-n Yes! using directly the port 55901 works perfectly!! Wow, absolutely impressed 👍 

I wish to be the first going production with this! I'm currently hosting a 97d to the public I'd love to use this backend for it!

Also, I was wondering if I could ever be able to slim down a season6 (removing skills, characters) etc... to get closer to have a 97d gameplay, I would just keep the events, maps and some set 😄 

Anyway, do you think is it something that can be fixed the connection between connect server and game server?

**Comment by sven-n** [comment]
Sure, slimming down the server is pretty easy. You’d just have to remove all the new stuff (NPCs, Maps, Items etc.) from the GameConfiguration.

The connect server can be fixed, I’m sure ;)

**Comment by sven-n** [comment]
I found and fixed the connect server issue. I wonder why it didn't come up earlier, it somehow worked magically before when all runs on the local machine.
I had to adjust my firewall settings to make the correct behavior work on my setup... really strange.

**Comment by sven-n** [comment]
Oh, and if you tried the admin panel live map and wonder that there is no map texture - there is an issue with SkiaSharp on linux. I'm trying to fix this next.

**Comment by fenos** [comment]
Awesome @sven-n !! 
I’ll be giving it a try sometime tonight and play more with items potentially fix some bug! 
Keep up the good work, the code base it’s great to read trough

**Comment by fenos** [comment]
My next step will be to plug PostgreSQL using docker compose, then I’ll be porting this to kubernetes too (helm chart).

This will allow to launch a production ready environment with few commands

**Comment by sven-n** [comment]
Thanks, sounds great :)

**Comment by fenos** [comment]
@sven-n Hi there!

I found some time yesterday to continue with the dockerization. although I still encounter the issue of clicking in the server and getting disconnected (even after rebuilding the image after pulling master)

How did you solve the issue? You mentioned some firewall settings, what about?

**Comment by sven-n** [comment]
I had to allow NAT edge traversal for these ports at the firewall of my windows host.

**Comment by sven-n** [comment]
I updated to .net core 2.2 recently, so you might need to adapt your docker file ;-)
Did you get it working on your local machine yet?

**Comment by sven-n** [comment]
I managed to create an azure pipeline which builds and pushes an image for the newest master branch to docker hub.
Here is the link: https://hub.docker.com/r/munique/openmu

**Comment by fenos** [comment]
@sven-n wow! that looks lovely! I've been slightly busy lately i should be going back to kube manifest and docker-compose soon

**Comment by sven-n** [comment]
Hey @fenos, we finally managed to set up OpenMU + Postgres by docker-compose with PR #132. Therefore, I'll close this issue for now.
If you have ideas for improvements, please don't hesitate to create a new issue.

Thank you again for your help :)
