### ISSUE TITLE
Guide setup the full flow connect from Client to Server

### ISSUE THREAD

**Issue by thinhnotes** [MUnique/OpenMU#139]
Hi Team, 

In current I had deployed success on the docker machine, but I had the client to connect it,  Would you like to provide a client on the current you used or connected from client to server.

I hope a guide to setup the client can be connect to it to play game.

Thanks,

**Comment by sven-n** [comment]
I can't provide a game client due to legal reasons. See also #14.

**Comment by thinhnotes** [comment]
thanks for support
