### ISSUE TITLE
season6 ep3 client or main.exe download url???

### ISSUE THREAD

**Issue by dusksoft** [MUnique/OpenMU#14]
season6 ep3 client or main.exe download url???

**Comment by sven-n** [comment]
I'm sorry, but for legal reasons I can't provide client files here.
You may have a look at the ragezone forums. The client version you need is 1.04d.

**Comment by nitoygo** [comment]
I was about to ask the same question. :D

By the way, is there an available FAQ/wiki page that lists these type of questions?

**Comment by sven-n** [comment]
Hello, unfortunately not yet. I’ll try to find time to start a wiki page for that ;)
