### ISSUE TITLE
can't connect client to server

### ISSUE THREAD

**Issue by thinhnotes** [MUnique/OpenMU#140]
Hi Team, 

In current I had start server on the docker with your document with command on docker 
`docker run --name openmu -d -p 1234:1234 -p 44405:44405 -p 55901:55901 -p 55902:55902 -p 55903:55903 -p 55980:55980 munique/openmu:latest -demo`
and it will be successfull with the log 
![image](https://user-images.githubusercontent.com/4660531/68539716-4aaeee00-03ba-11ea-8c58-beb05cba40ab.png)

And I config the client and connect to the server with information bellow with my ip is 192.168.1.123
![image](https://user-images.githubusercontent.com/4660531/68539726-6adead00-03ba-11ea-9432-f52e2f71564a.png)

When I start client I see the server to connect 
![image](https://user-images.githubusercontent.com/4660531/68539737-8d70c600-03ba-11ea-97cb-5318d229142d.png)
But when I join the server it will be disconect with images bellow:
![image](https://user-images.githubusercontent.com/4660531/68539746-b42efc80-03ba-11ea-92b9-522267d8eb91.png)
And the docker not any more log to show me what going on 
![image](https://user-images.githubusercontent.com/4660531/68539759-ce68da80-03ba-11ea-96c1-dba477f5b267.png)

Would you help me to take a look with it, how can I access the server by the client.

Thanks,

NotesVn

**Comment by sven-n** [comment]
Hi, do you run docker on windows? If yes, you might need to make the ports available through the firewall and to activate NAT Edge Traversal in the advanced firewall settings.

**Comment by thinhnotes** [comment]
yes, I run on the docker on windows and I had disabled the firewall but I can access the server, Do you have any advice?

**Comment by sven-n** [comment]
Docker and networking is a topic on its own :-/
I don’t even know if a season 12 client still uses the same connect server protocol.

What I can tell is, the connect server returns the IP and port which you can find in your log screenshot, when you click on a server. So, this endpoint needs to be accessible for your game client.
You can also try to use the -local parameter, but I‘m not sure if it works in a docker container.

**Comment by thinhnotes** [comment]
what current version of client for your testing?

**Comment by sven-n** [comment]
Version 1.04d English, Season 6 Episode 3

**Comment by thinhnotes** [comment]
i will try it and let you know if any more question, I hopefully it working and I will make a game with my friend, thanks

**Comment by thinhnotes** [comment]
I just download the version the Version 1.04d English, Season 6 Episode 3, but it not any goods news, it can see the server 
![image](https://user-images.githubusercontent.com/4660531/68548143-47e4e500-041c-11ea-94a8-d3769192dbdb.png)

But when I click to join the any server it will be return disconected
![image](https://user-images.githubusercontent.com/4660531/68548166-782c8380-041c-11ea-8f41-03a005b4d870.png)
and not any new log
![image](https://user-images.githubusercontent.com/4660531/68548175-8ed2da80-041c-11ea-9f98-3d0b282b1f4e.png)

Could you help me a take a look with it

**Comment by sven-n** [comment]
That’s not so easy as I don’t know your complete environment.
Just a hint: You could try to directly launch your client to a gameserver port, e.g. 55901.

**Comment by thinhnotes** [comment]
> That’s not so easy as I don’t know your complete environment.
> Just a hint: You could try to directly launch your client to a gameserver port, e.g. 55901.

I just used the game server port and it show the popup
![image](https://user-images.githubusercontent.com/4660531/68565280-9e3a3e00-0485-11ea-93db-3df812c6f4fd.png)

Do you have any idea

**Comment by sven-n** [comment]
Sorry for the late answer.
That's simple: Without further modification of the server, you'd need to use a Season 6 Episode 3 Client (1.04d English).

I don't know how many things of Season 6 are still the same in Season 12, so I can't even tell you which features work and if you can even enter the game with it.

**Comment by thinhnotes** [comment]
Hi, Would you like to explain more about the param -local, in current I run it on the visual studio on run with mode -local, it can be access the server, but If not the param it can NOT connect the server

I used the mode -local on the docker on linux, but it can NOT access the server.

Do you have any idea for it.

Thanks

**Comment by thinhnotes** [comment]
In current i had access the server, thanks for all support.

**Comment by sven-n** [comment]
No problem. I hope I can improve the configs a bit in the future, e.g. by specifying a custom IP as parameter

**Comment by thinhnotes** [comment]
> No problem. I hope I can improve the configs a bit in the future, e.g. by specifying a custom IP as parameter

I waiting for it, many thanks

**Comment by thinhnotes** [comment]
I had create pull to it, please help me to review it and let me know if it not good or any to change
https://github.com/MUnique/OpenMU/pull/141

Thanks

**Comment by BuuChau** [comment]
@thinhnotes @sven-n  Hi Bro, I'm new to this. I try run server and client, but when login ingame i has error :
![image](https://user-images.githubusercontent.com/16359854/125161187-1735ef80-e1ab-11eb-9c08-462d8288a2e0.png)
============
I try change mod before run Startup
![image](https://user-images.githubusercontent.com/16359854/125161238-6419c600-e1ab-11eb-999f-ee9a793d29c1.png)
============
Can you help me , please.
Thanks

**Comment by BuuChau** [comment]
Can you talking about version :
Server i see : 

![image](https://user-images.githubusercontent.com/16359854/125163098-a8aa5f00-e1b5-11eb-8af7-61922387b89b.png)
=====
Client : 

![image](https://user-images.githubusercontent.com/16359854/125163105-b8c23e80-e1b5-11eb-9d3a-b075f905ba59.png)

**Comment by sven-n** [comment]
you need client version 1.04d (1.04.04)

**Comment by BuuChau** [comment]
> you need client version 1.04d (1.04.04)

I can upgrade version in server ?

**Comment by hieuvtd00195** [comment]
![image](https://github.com/user-attachments/assets/51f24c36-7920-4135-90c4-226d62514d9d)
any help me

**Comment by Meir-Tools** [comment]
I have the same issue , anu help ?

**Comment by umanzel** [comment]
> In current i had access the server, thanks for all support.

how you solved?
