### ISSUE TITLE
Use Blazor instead of React in the AdminPanel project

### ISSUE THREAD

**Issue by MarioGK** [MUnique/OpenMU#147]
Hi, i have been away from the project for quite a while, but i am still coming back to know the progress from time to time.

Could we not use Blazor instead of React for the MainWebsite and the AdminPanel?
afaik you want to keep everything C# based.

**Comment by sven-n** [comment]
Hi, welcome back :)
Yes, I planned with Blazor, too. I would use Blazor for the AdminPanel and just normal Razor for the web site. Unfortunately, my time for this Project is pretty limited at the moment :-/
I would like to refactor the composition of the whole project first, also for a web api (#125).

I'm also thinking about how much scope this project should have, as there are websites which could be adapted to be compatible (e.g. WebEngine) and it's a big topic of its own.

**Comment by MarioGK** [comment]
Well in March the Client Side Blazor will be released, that would be perfect for the MainWebsite(if you want to do that).
The server side version would be perfect for the admin panel, you have access to the server without any kind of API.

I have not tried to help more because your coding style is really different from mine, if you are disposed to help me out on fixing my style and some bugs, i can try start doing the WebAPI(with this finished i can port my Launcher to .Net Core 3 and resume working on it as well) and the Websites.
