### ISSUE TITLE
A place to communicate [Non-issue]

### ISSUE THREAD

**Issue by layer07** [MUnique/OpenMU#148]
sven-n, you would kindly create a Discord group so we can gather some developers on the same corner? I've developed clientless bots for MU from scratch (I've been doing it since... 2005)...

If you can create a Discord server, I would like to have a word with people who are constantly developing for MU (such as myself and you) so we can share some ideas.

Feel free to close this if you find it not necessary,

Regards,

**Comment by sven-n** [comment]
Hello, since you're not the first who requested this, I registered at Discord and created a Server.
You can join it with this link: [https://discord.gg/2u5Agkd](https://discord.gg/2u5Agkd)
