### ISSUE TITLE
DropLevel for event items

### ISSUE THREAD

**Issue by sven-n** [MUnique/OpenMU#150]
### Affected event items:
* Blood Bone  
* ArchangelScroll
* Devils Key
* Devils Eye
* Old Scroll
* Illusion Sorcerer Covenant 

### A few issues:
* Currently, EventItems are initialized without a drop level ( https://github.com/MUnique/OpenMU/blob/master/src/Persistence/Initialization/Items/EventTicketItems.cs )
* Event Items should never exist with item level 0, but currently they drop
* Event Items must be dropped for higher levels than currently level 4
* The level spacing between even item drop levels are much bigger (see example below) than for normal items (every 3 monster levels is one item level)

### Example for Blood Castle event items
(Source: https://wiki.infinitymu.net/index.php?title=Blood_Castle_Event )
```
Who drop those items?
Items | Drop level | from Monsters
Scroll of Archangel +1 & Blood Bone +1 | Over LV. 2 | Spider
Scroll of Archangel +2 & Blood Bone +2 | Over LV. 32 | Ghost
Scroll of Archangel +3 & Blood Bone +3 | Over LV. 45 | Vepare
Scroll of Archangel +4 & Blood Bone +4 | Over LV. 57 | Death Cow
Scroll of Archangel +5 & Blood Bone +5 | Over LV. 68 | Silver Valkyrie
Scroll of Archangel +6 & Blood Bone +6 | Over LV. 76 | Bloody Wolf
Scroll of Archangel +7 & Blood Bone +7 | Over LV. 85 | Vim Knight
```

### How to fix:
* Extension of the ItemDefinition to be able to define a drop level per item level, e.g. as collection.
* Adapting the logic in ItemDropGenerator: When such entries exist for an item, the default logic should not be applied, but these entries must be applied.

Related issues: #23, #146

**Comment by sven-n** [comment]
I think this can be fixed in another way:

In the quest branch, I had to extend the DropItemGroup by a min and max drop level (https://github.com/MUnique/OpenMU/commit/0bcfd7c30756e70c935e6ad96f6af3b43873fda6). If we build the fix on it, we could simply add a property of "ItemLevel" and define DropItemGroups for the event ticket items. Additionally, the "DropsFromMonsters" must be changed to false for these items. "DropsFromMonsters" defines, if the item is dropping automatically by the standard random item drop logic. Maybe a rename would make sense, too.

**Comment by foxrj21** [comment]
nice
