### ISSUE TITLE
[GameLogic] /item chat command

### ISSUE THREAD

**Issue by jhonynet** [MUnique/OpenMU#161]
For all kind of testing propuse i've been working on `/item` command.

`/item Group Number Level Durability Skill Exc Opt Ancient`

**Comment by sven-n** [comment]
Nice 👍🏻 Had this in my big todo list, too 😄

**Comment by jhonynet** [comment]
In the first version of the command the arguments will be the followings
/item {Group} {Number} {Level} {Exc} {Skill} {Luck} {Opt}

Group (byte): Item Group
Number (sort): Item Number 
Level (byte): **0-15**
*Exc (byte): Limit the ItemOptions(excellent) collection (sorting comes from db engine) **0-N**
*Skill (bool): Add skill to item (excellent override this value) **0-1**
*Luck (bool): Add luck to item **0-1**
*Opt (byte): add option to item **0-4**

(*) Optional Arguments

next release may contain socket and ancient options?
