### ISSUE TITLE
[Feature] Reset System

### ISSUE THREAD

**Issue by jhonynet** [MUnique/OpenMU#171]
I open this issue to track the reset system progress
Branch **feature/reset_system**

Checklist:
- [x] Add `Reset` as StatAttribute
- [x] Add `ResetStatAttribute` to all characters definition
- [x] Add ResetAction
- [x] Add ResetCommand
- [x] Add Reset NPC 
_Leo the helper in Lorencia (130, 126) it can be disabled setting false to IsEnabled property in ResetCharacterAction.cs_

Nice to have:
* Option for a required item and quantity (like SCF files)
* Configurable points after N quantity of resets (250 points up to 20 reset, 350 up to 30, etc...)

Any ideas are welcome!

**Comment by sdyalor** [comment]
Please no.

**Comment by sven-n** [comment]
> Please no.

I also don't like resets, but that's just my personal preference. I'm fine with adding it, if it's optionally (like planned here).

**Comment by jhonynet** [comment]
i think this is ready to go as version 1 of reset system...

This introduce a new Strategy Plugin `ICustomNpcTalkHandlerPlugin.cs` and one implementation of it in `ResetCharacterNpcPlugin.cs`.
Later in `TalkNpcAction.cs` after call for generic plugin handler (line: 62), if none handled the event, looks for more specific handler by npc Number.
This is how i implemented the custom talk handler for `Leo the 'reset' helper` npc in Lorencia.

**Comment by sven-n** [comment]
Okay, nice 👍🏻 
I‘ll check it out hopefully tomorrow. Quite busy these days 🙈

**Comment by jhonynet** [comment]
@sven-n i made a quick test with the lasts commits and NPC is not working.
"Talking to this NPC (371 Leo the helper) is not implemented yet".
I don't know why is that. I checked the code and should be working :S

**Comment by sven-n** [comment]
Did you have resets enabled? If not, the Plugin did not set eventArgs.HasBeenHandled to true and this message appeared.

Now it should work ;)

**Comment by jhonynet** [comment]
Yes, that is the idea. it was my mistake in the test, works like a charm!!!

**Comment by sven-n** [comment]
I think we can close it now.
It’s now configurable at the admin panel at Plugins -> Reset Feature -> Config Button.
