### ISSUE TITLE
Add Monster Spell

### ISSUE THREAD

**Issue by And3rsL** [MUnique/OpenMU#177]
Some Monsters can cast spells
Example: Dungeon WIzard (and lorencia) can cast lightining

Currently its not supported

**Comment by sven-n** [comment]
Yes, it's not implemented yet. Some Monsters can even cast multiple spells, which we would need to consider when implementing it.

**Comment by sven-n** [comment]
I wrote a Regex to find monsters with skills in a Monsters.txt config file:
```regex
^(\d+)\s+\d+\s+"[^"]+"\s+\d+\s+\d+\s+\d+\s+\d+\s+\d+\s+\d+\s+\d+\s+\d+\s+\d+\s+\d+\s+([1-9]\d*)
```
First group is the monster number, second group is the skill number.
