### ISSUE TITLE
When an item can't be moved, send proper response

### ISSUE THREAD

**Issue by sven-n** [MUnique/OpenMU#19]
Currently, when an item can't be moved to the requested item slot of the inventory, the client gets no response and gets stuck - item stays at the mouse cursor and can't be dropped/moved somewhere else.
E.g. when trying to equip an item, it just says "You can't wear this item" and that's it.

**Comment by sven-n** [comment]
See also https://github.com/MUnique/OpenMU/blob/7bd8afa5e5bea8da16afaa7b45f2412714a2f2a5/src/GameLogic/PlayerActions/Items/MoveItemAction.cs#L55

**Comment by navossoc** [comment]
Probably you are looking for [PMSG_ITEMTHROW_RESULT](https://github.com/Fenrisus/p4f-free-emu/blob/491cd7a879f53efd153a44a1f077722e0013eaff/eGS/eGS/Header/protocol.h#L142) message.

C1 XX 23 Result Ipos
[BYTE] Result = 0 (false, don't drop)
[BYTE] Pos = item index (var `fromSlot` probably)

[]'s

**Comment by sven-n** [comment]
Thanks for your input. Are you sure that it's an "item throw result"?
What fails is an item movement, so I would assume that I need to send a PMSG_INVENTORYITEMMOVE_RESULT with result = 0xFF (-1) or 0x00 (not sure yet).
C1 xx 24 FF 00 ...

**Comment by sven-n** [comment]
Just tested it... the server was already sending C1 xx 23 when I tried to drop the item which I couldn't move. Then I tested further, and the server actually needs to send C3 xx 24 FF 00... to get the item back to the previous inventory position.

**Comment by navossoc** [comment]
Sorry, I read wrong, you're right.
