### ISSUE TITLE
Simplistic configurations files.

### ISSUE THREAD

**Issue by R3DIANCE** [MUnique/OpenMU#195]
**Is your feature request related to a problem? Please describe.**
no.

**Describe the solution you'd like**
Simplistic configurations can be set/read from files like game server - connect server settings as ini or json files.

also maybe file watcher to auto hot reload them.
ex.

- Main GameConfiguration -> CharacterNameRegex, MaximumLevel, ExperienceRate ,etc
- Gates
- JewelMixes
- etc..

**Comment by sven-n** [comment]
Thanks for your request.
For several reasons, I'm not a big fan of config files. I know, editing a big amount of config data over the admin panel is a bit troublesome, but there is still the option of directly working on the database. If you're a SQL ninja, this can be a very powerful tool.
And what I don't like about auto reloading of any files: It's difficult when you host the server somewhere where you don't have (or don't want to have) direct access to the file system, e.g. in container or cloud hosting situations.

I have another idea, though: What about some import functions in the admin panel? Something like:
* User navigates to a page which offers this import (e.g. the JewelMixes of a GameConfiguration)
* Somehow magically, an import button appears if there is some importer implemented for that type
* User clicks on an import button
* User selects a file (e.g. in the traditional format) from his computer
* User clicks okay
* Importer takes the data of this file and does all the parsing and imports that into the database

The last step is probably the one with the most work to do ;-)

If anyone has other ideas, feel free to express :)

**Comment by sven-n** [comment]
Closing that for now, since the admin panel gets better and better... ;-)
