### ISSUE TITLE
ILoggerFactory startup exception

### ISSUE THREAD

**Issue by wfxpanisa** [MUnique/OpenMU#197]
When trying a a startup via VS2019 there is multiple instances of the exception describe below

PluginManager.cs:332

System.InvalidOperationException: 'Unable to resolve service for type 'Microsoft.Extensions.Logging.ILoggerFactory' while attempting to activate 'MUnique.OpenMU.PlugIns.StrategyPlugInProvider`2[System.String,MUnique.OpenMU.GameLogic.PlugIns.ChatCommands.IChatCommandPlugIn]'.'

It seems to related to dotnet 3 update https://github.com/dotnet/extensions/issues/1096 but I do not understand the codebase sufficiently to confirm it right now.

**Comment by sven-n** [comment]
Thanks for the bug report, I fixed it :)
