### ISSUE TITLE
Unable to host ASP.NET with docker compose

### ISSUE THREAD

**Issue by kidtad** [MUnique/OpenMU#209]
**Describe the bug**

**To Reproduce**
1. When i run docker compose docker-compose up -d --build
2.docker-compose run -d munique -resolveIp:local
3.Docker log show error container with name munique/openmu you can see Screenshots

**Expected behavior**
docker compose run success

**Screenshots**
![image](https://user-images.githubusercontent.com/45290491/103770421-8eea5c80-5058-11eb-9590-b87f1f2d6d3a.png)

**Desktop (please complete the following information):**
 - Window 10

**Comment by sven-n** [comment]
I think you need to create a certificate like described here: https://github.com/MUnique/OpenMU/blob/master/QuickStart.md#generates-certificate

Alternatively, you could deactivate the public api by providing the *-api:disable* parameter

**Comment by kidtad** [comment]
@sven-n can you help me how to get my certificate password thank

**Comment by sven-n** [comment]
I don't understand your question. You create the password yourself and you should keep it secret.
