### ISSUE TITLE
full linux install guide & system req

### ISSUE THREAD

**Issue by rursi** [MUnique/OpenMU#211]
full linux install guide & system req.

**Comment by najoast** [comment]
# OS
CentOS 7 must be used, other versions of the OS are beyond the scope of this article.
I tried CentOS 6.x before, the .Net environment was not installed well, and I forgot where it was stuck. Anyway, 6.x is very troublesome, so it is best to use 7. The installation of the .Net environment will be very smooth, and the official has done 7. Very good support. I don’t want to support it before 6. I have to upgrade a lot of things.

# PostgreSQL
A version >= 9.3 must be installed, the previous version does not support the following syntax:
```
CREATE SCHEMA IF NOT EXIST
```
Will cause startup failure
```
2019-07-03 09:41:01,673 [1] DEBUG Npgsql.NpgsqlCommand [(null)]-Executing statement(s):
CREATE SCHEMA IF NOT EXISTS data

Unhandled Exception: Npgsql.PostgresException: 42601: syntax error at or near "NOT"
```

[This document](https://www.postgresql.org/docs/9.3/sql-createschema.html) talks about the syntax of `CREATE SCHEMA`, you can cut to 9.2 to look at it, and found that IF NOT is not supported .

### Install PostgreSQL 9.6
I originally wanted to install 9.3, but I found that this version is also very old. I can’t find the tutorial on the Internet. Only one link is invalid. So install 9.6 directly. This is [tutorial](http://yallalabs.com/ linux/how-to-install-postgresql-9-6-on-centos-7-rhel-7/).

After installing the tutorial, you will find that you can’t log in when you log in. There is one step missing. After the installation is complete, you must first set a password for the postgres user:

```bash
#Step 4: Accessing Database
passwd postgres
# then input you password twice
su – postgres
psql
```

#### Set public network access

#### Modify postgres password

#### Change the password authentication method to md5



# Install .Net environment
https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/install

```
sudo rpm -Uvh https://packages.microsoft.com/config/rhel/7/packages-microsoft-prod.rpm
sudo yum update
sudo yum install dotnet-sdk-2.2
dotnet
```

# Compile
Pull the code first
```
git clone https://github.com/MUnique/OpenMU.git
```
The current code needs to modify 1 csproj file to compile correctly:
https://github.com/najoast/OpenMU/commit/de3d3234ca5713b36e39e0cd84bebdacb6e7f3a7

# Run
There are two ways
1. Enter the OpenMU/src/Startup directory, dotnet run -autostart -demo
2. After compiling, enter the OpenMu/bin/Debug directory, dotnet MUnique.OpenMU.Startup.dll -autostart -demo

**Comment by rursi** [comment]
Thanks but what about cpu ,ram ?

**Comment by sven-n** [comment]
Some people had it working on the cheapest DigitalOcean Droplets. So I assume, it works on low end machines without problems (for an unknown amount of players...). It's not optimized for RAM usage, though. So after start, it takes about 400 mb of ram, because it caches a lot of things for best performance.

**Comment by rursi** [comment]
i get this error 
![error](https://user-images.githubusercontent.com/77249662/107366246-9339e780-6ae6-11eb-9556-6aec3a77e3e7.png)

**Comment by sven-n** [comment]
@rursi can you try it again? I updated some involved nuget packages.

**Comment by mradkov** [comment]
> Thanks but what about cpu ,ram ? i want start 97d version game server.On my vps. ...

So does this repo contain 0.97d version as well?

**Comment by sven-n** [comment]
@mradkov not yet. Currently, it has support for 0.75, 0.95d and 1.04d (Season 6)

**Comment by sven-n** [comment]
I'm closing this now. At the moment I can just give the hint to use docker-compose for deployment, as it makes things much easier.
Creating (and maintaining!) guides for all kinds of linux distros just takes a lot of time and energy. If you want to do that, you can send pull requests, though.
