### ISSUE TITLE
can i get a  ARMv8 docker ？

### ISSUE THREAD

**Issue by jimmieyangcsjs** [MUnique/OpenMU#233]
can i get a  ARMv8 docker ？ please

**Comment by sven-n** [comment]
I don't understand your request. When you run docker on a ARMv8 linux system, it will pull the right stuff for your CPU architecture automatically.

See: https://andrewlock.net/creating-multi-arch-docker-images-for-arm64-from-windows/

> On a Linux system, this would pull the x64, arm64, or arm32 image, depending on your host architecture!
