### ISSUE TITLE
[Support] Generate certificate on linux

### ISSUE THREAD

**Issue by TheDarthFather** [MUnique/OpenMU#240]
Hello,\
I installed the docker version on a Ubuntu 20.
I am afraid the lines below dont work as they are ... anything I am missing ?

```
source dev.sh
generate_certificates { password here }
```

**Comment by sven-n** [comment]
Did you replace `{ password here}` with your own password? ;-)

**Comment by TheDarthFather** [comment]
Sorry I was not clear ...

```
root@doc:/var/lib/docker/image/openmu# source dev.sh
-bash: dev.sh: No such file or directory
```

**Comment by sven-n** [comment]
The guide is probably not clear, too.
You need to download the [dev.sh](https://github.com/MUnique/OpenMU/blob/master/dev.sh) to your host machine, before you can execute this command.

**Comment by TheDarthFather** [comment]
Ah, lol :)
PS: I did not understand the `source dev.sh` at all .. now makes sense :)

**Comment by TheDarthFather** [comment]
It seems I am still missing something  !?
https://pastebin.com/xu7r8xFH

**Comment by sven-n** [comment]
Have you managed to get it working?
Unfortunately, I can't help you much with that, as I don't have experience using a linux host :-(

**Comment by TheDarthFather** [comment]
No, I havent try anything else after - no much time. I will when/if I get more time to 'study' :)
