### ISSUE TITLE
Share Zen between Party members.

### ISSUE THREAD

**Issue by Mosch0512** [MUnique/OpenMU#242]
It would be a nice optional feature if implementable, to have ZEN sharing between group members.

Ech Group member gets 1/n part of the zen value and if amount is not splitable without reminder than the player who picked the zen up should get the reminder.

**Comment by sven-n** [comment]
It should already work, because it's implemented in Party.DistributeMoneyAfterKill(...). The players which receive the money must be in range of the killed monster, though.
Can you confirm, that it doesn't work?
