### ISSUE TITLE
Wrong Respawn Locations

### ISSUE THREAD

**Issue by Mosch0512** [MUnique/OpenMU#304]
**Describe the bug**
If you die in Icarus you will be warped to Lorencia instead of Lost Tower 1.
If you die in Karutan 2 you will be warped to Lorencia after #268 or Karutan 2 again with current Master branch.

Wrong spawns

1. Santa Village
2. Raklion Boss
3. Icarus
4. Karutan 2

**To Reproduce**
1. Go to Icarus/Karutan 2
2. Get Killed
5. Respawned at Lorencia

**Expected behavior**
Respawn at Lost Tower 1/ Karutan 2

**Additional context**
#268 has nothing to do with that

**Comment by sven-n** [comment]
To fix that in the initalization logic or Icarus or Karutan, we can override the SafezoneMapNumber of their BaseMapInitializer implementations.

**Comment by Mosch0512** [comment]
But this means it is not changable for normal users without touching the code.

Wouldnt it be nicer to have an Database Table for each maps spawn map/location/are would make it more accessible

**Comment by sven-n** [comment]
That's already the case. All of this code in MUnique.OpenMU.Persistence.Initialization creates the data in the database on the first start of the server (or with -reinit parameter).
The user can change that afterwards in the database or in the admin panel, of course.

**Comment by sven-n** [comment]
![grafik](https://user-images.githubusercontent.com/5238610/206551928-fb43d566-7fbb-4bc0-9eb7-46ccc5e7db0f.png)

**Comment by Mosch0512** [comment]
okay i will fix the initialization for these maps than :D
