### ISSUE TITLE
ARM64 Docker Image

### ISSUE THREAD

**Issue by jimmieyangcsjs** [MUnique/OpenMU#332]
Can developers create a container image of arm64 architecture? thanks！

**Comment by sven-n** [comment]
Some good news: https://devblogs.microsoft.com/dotnet/improving-multiplatform-container-support/

**Comment by sven-n** [comment]
I'm doing some tests right now and creating arm images over azure pipelines seems to work 🚀
I'll build them regularly soon, if no issues show up 👍

**Comment by sven-n** [comment]
![grafik](https://user-images.githubusercontent.com/5238610/231577066-46d2f914-f1fa-4637-a63a-7612d325fd66.png)
🎉 finally
