### ISSUE TITLE
Where can I get the game client version 0.75

### ISSUE THREAD

**Issue by leonliao78** [MUnique/OpenMU#337]
I got Client 1.04d ENG - Season 6 Episode 3 [here](https://forum.ragezone.com/threads/release-client-1-04d-eng-season-6-episode-3.1143697/)and it works. But I wanna try the old version 0.75. 
please give me some guidance if you know where to download the game client version 0.75.
Thank you very much!

**Comment by sven-n** [comment]
Please check our discord FAQ channel ;-)

**Comment by leonliao78** [comment]
> Please check our discord FAQ channel ;-)

Thanks a lot.I just downloaded the old version client from discord FAQ and found it doesn't work.

**Comment by sven-n** [comment]
What exactly doesn't work?

If you can't connect at all, you'd probably change the IP in the main.exe with a hex editor.

On the server side, you'd need to run the setup over the admin panel with the right version.
