### ISSUE TITLE
Skype?

### ISSUE THREAD

**Issue by Anchorist** [MUnique/OpenMU#34]
Tremendous work!, do you have skype or some other instant messaging? I got couple of questions regarding protocol handling.

**Comment by sven-n** [comment]
Hi, I'm glad you like the project :)

Well, there is a reason why GitHub has no private message system. I also prefer to answer your questions here, so other people can benefit, too.
If you really need to send me private messages, you can send me your Skype name at RaGEZONE - my nickname is nevS there.
