### ISSUE TITLE
Guard NPC behavior

### ISSUE THREAD

**Issue by sven-n** [MUnique/OpenMU#346]
**Is your feature request related to a problem? Please describe.**

Currently, the guards (e.g. at the entrances to the safezones) are not doing anything. They just stand around.
AFAIK, in the original server, they attack players which have a player kill status.

**Describe the solution you'd like**

* Implement a new INpcIntelligence for Guards
* Specify the implementation as the ```MonsterDefinition.IntelligenceTypeName``` for all guards in the Initialiation project.

**Comment by tradi3** [comment]
Step 1: Create a new class for the guard intelligence

Create a new class file called GuardsIntelligence.cs in the appropriate directory (e.g., GameServer/GameLogic/NPC/Intelligence) of the OpenMU source code project. In this class, implement the INpcIntelligence interface and the necessary logic for the guard's behavior.

```
using GameServer.GameLogic.NPC;

namespace GameServer.GameLogic.NPC.Intelligence
{
    public class GuardsIntelligence : INpcIntelligence
    {
        public void Update(NpcInstance npc)
        {
            // Implement the logic to update the guard's behavior
            // For example, check nearby players and attack those with a player kill status
        }
    }
}
```

Step 2: Update the guard monster definitions

In the MonsterDefinition.cs file, locate the guard monster definitions (e.g., for guards at the entrances to safe zones). Assign the fully qualified name of the GuardsIntelligence class to the IntelligenceTypeName property of these guard monster definitions.



```
namespace GameServer.GameLogic
{
    public class MonsterDefinition
    {
        // Other properties and methods
        
        public string IntelligenceTypeName { get; set; } = "GameServer.GameLogic.NPC.Intelligence.GuardsIntelligence";
        
        // Other properties and methods
    }
}
```

Step 3: Build the OpenMU source code project

Build the OpenMU source code project to compile the changes and ensure there are no compilation errors. Refer to the documentation or the specific instructions for building the OpenMU project based on the repository you are using.

Step 4: Run the updated OpenMU server

Run the updated OpenMU server and test the behavior of the guards. They should now attack players with a player kill status.
