### ISSUE TITLE
/skin command visual bug

### ISSUE THREAD

**Issue by juliancasaburi** [MUnique/OpenMU#357]
**Describe the bug**
The /skin command displays an incorrect skin to other players.

**To Reproduce**
1. Log in using a gamemaster character.
2. Log in using a normal character.
3. Use the /skin command followed by a valid monster number. For example, type "/skin 503" to select the Panda skin.
4. Observe the gamemaster character model while controlling the normal character.

**Expected behavior**
The gamemaster character model should match the skin chosen using the /skin command.

**Current behavior**
The gamemaster character model always appears as the Bull fighter, regardless of the skin number used. When using "/skin 0", the character detransforms entirely.

**Screenshots**
![skin_command_bug](https://github.com/MUnique/OpenMU/assets/48498042/627cc37c-935c-4695-aaa4-878e8c3fdd85)

**Comment by sven-n** [comment]
This bug has the same origin as #358. Fixed as well.
Thanks for reporting :)
