### ISSUE TITLE
Ring of transformation visual bug

### ISSUE THREAD

**Issue by juliancasaburi** [MUnique/OpenMU#358]
**Describe the bug**
When a player wears a ring of transformation in the game, the character's appearance is not correctly displayed to other players. Instead of showing the skin associated with the transformation ring, the character model appears as Bull Fighter. The incorrect skin persists until the ring is unequipped, at which point the character model returns to its normal appearance.

**To Reproduce**
1. Equip any ring of transformation on the character.

**Expected behavior**
When wearing the ring of transformation, the character model should be displayed to other players using the corresponding skin associated with the transformation ring.

**Current behavior**
The character model appears as Bull Fighter while the transformation ring is equipped. The incorrect skin persists until the ring is unequipped, at which point the character model returns to its normal appearance.

**Screenshots**
**Snowman Transformation Ring**
![ring_of_transformation_bug](https://github.com/MUnique/OpenMU/assets/48498042/b7265b28-f6f6-448b-997a-b8466c1bfd32)

**Budge Dragon Transformation Ring**
![ring_of_transformation_bug_budge_dragon](https://github.com/MUnique/OpenMU/assets/48498042/b3408cb9-a6ea-473e-b62e-45c7787e9975)

**Comment by sven-n** [comment]
Thanks, good catch!
