### ISSUE TITLE
[Bug] Stuck on "Please Wait" Box when Creating Character with Existing Name

### ISSUE THREAD

**Issue by juliancasaburi** [MUnique/OpenMU#374]
**Describe the bug**
When creating a character, if the chosen name is already in use, the client gets stuck with a "Please Wait" box and does not proceed with any further action.

**To Reproduce**
1. Launch the client and log in.
2. Click "Create" button.
3. Enter a character name that is already in use.

**Expected behavior**
The user should be able to choose a different name without getting stuck on a "Please Wait" box.

**Screenshots**

![character-create-duplicate-name](https://github.com/MUnique/OpenMU/assets/48498042/4903aa23-e86d-445b-bc76-6298140a3ca0)

**Additional context**

Server log:

> 2023-08-03 04:37:53.254 -03:00 [Error] [MUnique.OpenMU.GameLogic.Player] Error when trying to create character '"testName"'                                                                                                                  Microsoft.EntityFrameworkCore.DbUpdateException: An error occurred while saving the entity changes. See the inner exception for details.
---> Npgsql.PostgresException (0x80004005): 23505: duplicate key value violates unique constraint "IX_Character_Name"

**Comment by sven-n** [comment]
Thanks for reporting, I created a fix :)
