### ISSUE TITLE
Where can i download the MU Client?

### ISSUE THREAD

**Issue by sydney691** [MUnique/OpenMU#377]
I tried several clients but its not working. it is closing immediately when i run the main.exe. I did use your launcher and paste it inside the MU folder but when the MU Client runs it closes immediately. Where can i download the right MU client? Can you send me an instruction on  where to download the client and how to run the MU client

![image](https://github.com/MUnique/OpenMU/assets/20122919/942ec82b-d2cc-443a-b292-1a036dbebe2f)
![image](https://github.com/MUnique/OpenMU/assets/20122919/0a0541b3-5f23-4b23-8a72-f34a27070d13)
![image](https://github.com/MUnique/OpenMU/assets/20122919/1bcaf899-145e-48b8-970b-ca65cac4efd3)

**Comment by sven-n** [comment]
Please check our discord channel.
