### ISSUE TITLE
CPU 100% when the server is running 

### ISSUE THREAD

**Issue by zwingser** [MUnique/OpenMU#397]
**Describe the bug**
when the server is running .
cpu up to 100%, and these process is called.

im using the docker all in one deployment .
i can reproduce it in x86 and arm server .

at the begining , its ok ,after about 2weeks it happend.
![image](https://github.com/MUnique/OpenMU/assets/126068653/0a532b44-9b55-483e-b7f3-72aa6045fbfe)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by dege88** [comment]
Looks like your server got hacked with a criptominer: https://stackoverflow.com/questions/60151640/kdevtmpfsi-using-the-entire-cpu

**Comment by zwingser** [comment]
this is the only server i deploy on my vps ,and this is a new vps from oracle arm machine.

and when the OpenMU server is shutdown . the problem solved .

so , i think there mast be some problems inside the contianer .

**Comment by sven-n** [comment]
I'm sorry that this happened to you. Can you give us some information about how exactly you deployed that all-in-one with docker compose?
* Which ports does the container actually expose?
* Did you change the admin panel password?

**Comment by zwingser** [comment]
> I'm sorry that this happened to you. Can you give us some information about how exactly you deployed that all-in-one with docker compose?
> 
> * Which ports does the container actually expose?
> * Did you change the admin panel password?

1. i modify the ports .
2. i didnt change the password of admin panel
3.this is my startup script:
![1173f438c695411eb341a5df6af90197](https://github.com/MUnique/OpenMU/assets/126068653/6e5bc746-6056-43ce-9da0-2f41562af299)
4. and this is the compose file( only the 80 port was modified):
![48ff39957824443496a0e9d4ffa45c6c](https://github.com/MUnique/OpenMU/assets/126068653/e93fe0b2-26ba-4426-a0bf-df2eb827d761)

**Comment by sven-n** [comment]
Okay, I don't know how this cryptominer actually sneaked into that container, but I highly recommend to change the admin panel password.

**Comment by lucasfcnunes** [comment]
> Okay, I don't know how this cryptominer actually sneaked into that container, but I highly recommend to change the admin panel password.

@sven-n Is that specific to @zwingser container/setup or a CVE in the [MUnique/OpenMU](https://github.com/MUnique/OpenMU) project?

**Comment by lucasfcnunes** [comment]
Nothing detected here for now (on [91f97a0d0803](https://hub.docker.com/layers/munique/openmu/latest/images/sha256-220ab49a8f8c8c2b951322027221f7fe949b1148ca1512b5b4eb740f0e2a8b33?context=explore)).

![image](https://github.com/MUnique/OpenMU/assets/29926675/72e37173-00d3-4bd5-a2cc-fd578ce7558e)

**Comment by sven-n** [comment]
Unfortunately, I found a way how to get some code into the server when the admin panel is accessible. I fixed it for now. However, I'm not sure if that was the attack vector.
@zwingser Can you check if there is any result for this query on the database?
`SELECT * FROM config."PlugInConfiguration" WHERE "CustomPlugInSource" is not null`

**Comment by zwingser** [comment]
> Unfortunately, I found a way how to get some code into the server when the admin panel is accessible. I fixed it for now. However, I'm not sure if that was the attack vector. @zwingser Can you check if there is any result for this query on the database? `SELECT * FROM config."PlugInConfiguration" WHERE "CustomPlugInSource" is not null`

yesterday  i  remove the image & container & volumes , so i can not check it now .
i can try to rebuild it ,but im not sure when it will happen again.

**Comment by sven-n** [comment]
Okay, I'm closing this issue for now. If it happens again, open a new one or comment here.

**Comment by sven-n** [comment]
We found a way how a crypto miner could come into that. It was the exposed postgres port in traefik deployment, see #435.

@zwingser But you used the "normal" deployment with nginx, right? In that case, we also might have to change something to keep the postgres database more private than it already is.
