### ISSUE TITLE
Broken link on packets docs

### ISSUE THREAD

**Issue by GabrielLins64** [MUnique/OpenMU#399]
**Describe the bug**

Hi. On the [Packets Docs](https://munique.github.io/OpenMU/Packets/), the first link, for the individual packets docs, is broken.

**To Reproduce**

1. Go to '[https://munique.github.io/OpenMU/Packets/](https://munique.github.io/OpenMU/Packets/)'.
2. Click on '[MUnique.OpenMU.Network.Packets](https://munique.github.io/src/Network/Packets/).'
3. See error.

**Expected behavior**

Maybe the url of the href should be [https://github.com/MUnique/OpenMU/tree/master/src/Network/Packets](https://github.com/MUnique/OpenMU/tree/master/src/Network/Packets).

**Screenshots**

![image](https://github.com/MUnique/OpenMU/assets/42005625/3fd2478a-fdef-4280-9960-0ee0a112b468)

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04
 - Browser: Chrome
 - Version: 120.0.6099.129

**Comment by sven-n** [comment]
Fixed, thanks for reporting
