### ISSUE TITLE
Implement usage of ammunition (Arrows, Bolts) for Bows/Crossbows

### ISSUE THREAD

**Issue by sven-n** [MUnique/OpenMU#4]
At the moment, Bows and Crossbows can probably be used without consuming ammunition (Arrows, Bolts).

**Comment by sven-n** [comment]
Ideas:
* The durability of an item could act as a consumable stat attribute.
* A stat like “ammo consumption rate” which is 1 by default. Skills like Infinite Arrow multiply this stat by 0 via MagicEffect, so no consumption happens while the effect is active.
* Skills which need ammo have this stat attribute in their ConsumeRequirements.

**Comment by nmarazov** [comment]
I will start working on this feature.
