### ISSUE TITLE
The client cannot connect to the server.

### ISSUE THREAD

**Issue by 496080199** [MUnique/OpenMU#407]
The bug:
The client cannot connect to the server.

Client Version:
1.04d - Season 6E3

Errors on the server:

tdout: 2024-04-15 02:29:12.606 +00:00 [Error] [MUnique.OpenMU.Network.Connection] Connection will be disconnected, because of an exception
stdout: MUnique.OpenMU.Network.InvalidPacketHeaderException: The packet header is invalid: 47 45 54
stdout: Buffer position: 0
stdout: Buffer content: 47 45 54 20 2F 20 48 54 54 50 2F 31 2E 31 0D 0A 48 6F 73 74 3A 20 31 39 32 2E 31 36 38 2E 31 2E 32 35 32 3A 34 34 34 30 35 0D 0A 43 6F 6E 6E 65 63 74 69 6F 6E 3A 20 6B 65 65 70 2D 61 6C 69 76 65 0D 0A 55 70 67 72 61 64 65 2D 49 6E 73 65 63 75 72 65 2D 52 65 71 75 65 73 74 73 3A 20 31 0D 0A 55 73 65 72 2D 41 67 65 6E 74 3A 20 4D 6F 7A 69 6C 6C 61 2F 35 2E 30 20 28 57 69 6E 64 6F 77 73 20 4E 54 20 31 30 2E 30 3B 20 57 69 6E 36 34 3B 20 78 36 34 29 20 41 70 70 6C 65 57 65 62 4B 69 74 2F 35 33 37 2E 33 36 20 28 4B 48 54 4D 4C 2C 20 6C 69 6B 65 20 47 65 63 6B 6F 29 20 43 68 72 6F 6D 65 2F 31 31 39 2E 30 2E 36 30 34 35 2E 31 36 30 20 53 61 66 61 72 69 2F 35 33 37 2E 33 36 0D 0A 41 63 63 65 70 74 3A 20 74 65 78 74 2F 68 74 6D 6C 2C 61 70 70 6C 69 63 61 74 69 6F 6E 2F 78 68 74 6D 6C 2B 78 6D 6C 2C 61 70 70 6C 69 63 61 74 69 6F 6E 2F 78 6D 6C 3B 71 3D 30 2E 39 2C 69 6D 61 67 65 2F 61 76 69 66 2C 69 6D 61 67 65 2F 77 65 62 70 2C 69 6D 61 67 65 2F 61 70 6E 67 2C 2A 2F 2A 3B 71 3D 30 2E 38 2C 61 70 70 6C 69 63 61 74 69 6F 6E 2F 73 69 67 6E 65 64 2D 65 78 63 68 61 6E 67 65 3B 76 3D 62 33 3B 71 3D 30 2E 37 0D 0A 52 65 66 65 72 65 72 3A 20 68 74 74 70 3A 2F 2F 31 39 32 2E 31 36 38 2E 31 2E 32 35 32 2F 63 67 69 2D 62 69 6E 2F 6C 75 63 69 2F 61 64 6D 69 6E 2F 64 6F 63 6B 65 72 2F 63 6F 6E 74 61 69 6E 65 72 73 0D 0A 41 63 63 65 70 74 2D 45 6E 63 6F 64 69 6E 67 3A 20 67 7A 69 70 2C 20 64 65 66 6C 61 74 65 0D 0A 41 63 63 65 70 74 2D 4C 61 6E 67 75 61 67 65 3A 20 7A 68 2D 43 4E 2C 7A 68 3B 71 3D 30 2E 39 0D 0A 43 6F 6F 6B 69 65 3A 20 61 67 68 5F 73 65 73 73 69 6F 6E 3D 32 35 36 31 39 30 37 65 34 36 63 61 61 66 62 63 36 30 66 39 64 61 35 65 61 63 36 31 61 37 64 38 3B 20 6E 64 2D 70 6C 61 79 65 72 2D 36 31 36 34 36 64 36 39 36 65 3D 66 63 35 34 38 66 34 62 2D 61 65 61 66 2D 34 33 66 65 2D 39 30 61 35 2D 38 64 34 34 66 62 65 39 37 61 39 63 3B 20 4C 4F 42 45 5F 4C 4F 43 41 4C 45 3D 7A 68 2D 43 4E 3B 20 63 6C 6F 75 64 72 65 76 65 2D 73 65 73 73 69 6F 6E 3D 4D 54 63 78 4D 6A 55 30 4E 7A 49 32 4E 6E 78 4F 64 33 64 42 54 6B 56 57 57 6C 55 77 4D 55 68 54 4D 55 70 4C 56 32 78 47 55 56 5A 72 56 6C 52 58 52 45 70 57 55 57 74 6F 55 46 4A 46 4D 48 6C 54 56 57 78 51 55 32 73 35 51 6C 52 73 54 6C 46 53 4D 55 4A 54 55 31 52 4B 57 45 35 46 5A 7A 4A 56 56 54 6C 51 54 57 70 61 54 6C 4A 72 4E 48 6C 53 4D 55 55 39 66 43 62 5F 6F 77 75 36 45 47 77 72 72 77 65 6D 4C 66 4D 55 53 65 64 43 46 53 7A 2D 38 6A 77 6F 47 71 70 65 50 46 33 6E 6E 4F 6B 42 0D 0A 0D 0A
stdout: 2024-04-15 02:29:12.608 +00:00 [Error] [MUnique.OpenMU.Network.Connection] Connection will be disconnected, because of an exception
stdout: MUnique.OpenMU.Network.InvalidPacketHeaderException: The packet header is invalid: 47 45 54
stdout: Buffer position: 0
stdout: Buffer content: 47 45 54 20 2F 20 48 54 54 50 2F 31 2E 31 0D 0A 48 6F 73 74 3A 20 31 39 32 2E 31 36 38 2E 31 2E 32 35 32 3A 34 34 34 30 35 0D 0A 43 6F 6E 6E 65 63 74 69 6F 6E 3A 20 6B 65 65 70 2D 61 6C 69 76 65 0D 0A 55 70 67 72 61 64 65 2D 49 6E 73 65 63 75 72 65 2D 52 65 71 75 65 73 74 73 3A 20 31 0D 0A 55 73 65 72 2D 41 67 65 6E 74 3A 20 4D 6F 7A 69 6C 6C 61 2F 35 2E 30 20 28 57 69 6E 64 6F 77 73 20 4E 54 20 31 30 2E 30 3B 20 57 69 6E 36 34 3B 20 78 36 34 29 20 41 70 70 6C 65 57 65 62 4B 69 74 2F 35 33 37 2E 33 36 20 28 4B 48 54 4D 4C 2C 20 6C 69 6B 65 20 47 65 63 6B 6F 29 20 43 68 72 6F 6D 65 2F 31 31 39 2E 30 2E 36 30 34 35 2E 31 36 30 20 53 61 66 61 72 69 2F 35 33 37 2E 33 36 0D 0A 41 63 63 65 70 74 3A 20 74 65 78 74 2F 68 74 6D 6C 2C 61 70 70 6C 69 63 61 74 69 6F 6E 2F 78 68 74 6D 6C 2B 78 6D 6C 2C 61 70 70 6C 69 63 61 74 69 6F 6E 2F 78 6D 6C 3B 71 3D 30 2E 39 2C 69 6D 61 67 65 2F 61 76 69 66 2C 69 6D 61 67 65 2F 77 65 62 70 2C 69 6D 61 67 65 2F 61 70 6E 67 2C 2A 2F 2A 3B 71 3D 30 2E 38 2C 61 70 70 6C 69 63 61 74 69 6F 6E 2F 73 69 67 6E 65 64 2D 65 78 63 68 61 6E 67 65 3B 76 3D 62 33 3B 71 3D 30 2E 37 0D 0A 52 65 66 65 72 65 72 3A 20 68 74 74 70 3A 2F 2F 31 39 32 2E 31 36 38 2E 31 2E 32 35 32 2F 63 67 69 2D 62 69 6E 2F 6C 75 63 69 2F 61 64 6D 69 6E 2F 64 6F 63 6B 65 72 2F 63 6F 6E 74 61 69 6E 65 72 73 0D 0A 41 63 63 65 70 74 2D 45 6E 63 6F 64 69 6E 67 3A 20 67 7A 69 70 2C 20 64 65 66 6C 61 74 65 0D 0A 41 63 63 65 70 74 2D 4C 61 6E 67 75 61 67 65 3A 20 7A 68 2D 43 4E 2C 7A 68 3B 71 3D 30 2E 39 0D 0A 43 6F 6F 6B 69 65 3A 20 61 67 68 5F 73 65 73 73 69 6F 6E 3D 32 35 36 31 39 30 37 65 34 36 63 61 61 66 62 63 36 30 66 39 64 61 35 65 61 63 36 31 61 37 64 38 3B 20 6E 64 2D 70 6C 61 79 65 72 2D 36 31 36 34 36 64 36 39 36 65 3D 66 63 35 34 38 66 34 62 2D 61 65 61 66 2D 34 33 66 65 2D 39 30 61 35 2D 38 64 34 34 66 62 65 39 37 61 39 63 3B 20 4C 4F 42 45 5F 4C 4F 43 41 4C 45 3D 7A 68 2D 43 4E 3B 20 63 6C 6F 75 64 72 65 76 65 2D 73 65 73 73 69 6F 6E 3D 4D 54 63 78 4D 6A 55 30 4E 7A 49 32 4E 6E 78 4F 64 33 64 42 54 6B 56 57 57 6C 55 77 4D 55 68 54 4D 55 70 4C 56 32 78 47 55 56 5A 72 56 6C 52 58 52 45 70 57 55 57 74 6F 55 46 4A 46 4D 48 6C 54 56 57 78 51 55 32 73 35 51 6C 52 73 54 6C 46 53 4D 55 4A 54 55 31 52 4B 57 45 35 46 5A 7A 4A 56 56 54 6C 51 54 57 70 61 54 6C 4A 72 4E 48 6C 53 4D 55 55 39 66 43 62 5F 6F 77 75 36 45 47 77 72 72 77 65 6D 4C 66 4D 55 53 65 64 43 46 53 7A 2D 38 6A 77 6F 47 71 70 65 50 46 33 6E 6E 4F 6B 42 0D 0A 0D 0A
stdout: 
stdout:    at MUnique.OpenMU.Network.PacketPipeReaderBase.ReadBufferAsync() in /src/Network/PacketPipeReaderBase.cs:line 93
stdout:    at MUnique.OpenMU.Network.PacketPipeReaderBase.ReadSourceAsync() in /src/Network/PacketPipeReaderBase.cs:line 51
stdout: 2024-04-15 02:29:12.620 +00:00 [Error] [MUnique.OpenMU.Network.Connection] Connection will be disconnected, because of an exception
stdout: MUnique.OpenMU.Network.InvalidPacketHeaderException: The packet header is invalid: 47 45 54
stdout: Buffer position: 0
stdout: Buffer content: 47 45 54 20 2F 20 48 54 54 50 2F 31 2E 31 0D 0A 48 6F 73 74 3A 20 31 39 32 2E 31 36 38 2E 31 2E 32 35 32 3A 34 34 34 30 35 0D 0A 43 6F 6E 6E 65 63 74 69 6F 6E 3A 20 6B 65 65 70 2D 61 6C 69 76 65 0D 0A 55 70 67 72 61 64 65 2D 49 6E 73 65 63 75 72 65 2D 52 65 71 75 65 73 74 73 3A 20 31 0D 0A 55 73 65 72 2D 41 67 65 6E 74 3A 20 4D 6F 7A 69 6C 6C 61 2F 35 2E 30 20 28 57 69 6E 64 6F 77 73 20 4E 54 20 31 30 2E 30 3B 20 57 69 6E 36 34 3B 20 78 36 34 29 20 41 70 70 6C 65 57 65 62 4B 69 74 2F 35 33 37 2E 33 36 20 28 4B 48 54 4D 4C 2C 20 6C 69 6B 65 20 47 65 63 6B 6F 29 20 43 68 72 6F 6D 65 2F 31 31 39 2E 30 2E 36 30 34 35 2E 31 36 30 20 53 61 66 61 72 69 2F 35 33 37 2E 33 36 0D 0A 41 63 63 65 70 74 3A 20 74 65 78 74 2F 68 74 6D 6C 2C 61 70 70 6C 69 63 61 74 69 6F 6E 2F 78 68 74 6D 6C 2B 78 6D 6C 2C 61 70 70 6C 69 63 61 74 69 6F 6E 2F 78 6D 6C 3B 71 3D 30 2E 39 2C 69 6D 61 67 65 2F 61 76 69 66 2C 69 6D 61 67 65 2F 77 65 62 70 2C 69 6D 61 67 65 2F 61 70 6E 67 2C 2A 2F 2A 3B 71 3D 30 2E 38 2C 61 70 70 6C 69 63 61 74 69 6F 6E 2F 73 69 67 6E 65 64 2D 65 78 63 68 61 6E 67 65 3B 76 3D 62 33 3B 71 3D 30 2E 37 0D 0A 52 65 66 65 72 65 72 3A 20 68 74 74 70 3A 2F 2F 31 39 32 2E 31 36 38 2E 31 2E 32 35 32 2F 63 67 69 2D 62 69 6E 2F 6C 75 63 69 2F 61 64 6D 69 6E 2F 64 6F 63 6B 65 72 2F 63 6F 6E 74 61 69 6E 65 72 73 0D 0A 41 63 63 65 70 74 2D 45 6E 63 6F 64 69 6E 67 3A 20 67 7A 69 70 2C 20 64 65 66 6C 61 74 65 0D 0A 41 63 63 65 70 74 2D 4C 61 6E 67 75 61 67 65 3A 20 7A 68 2D 43 4E 2C 7A 68 3B 71 3D 30 2E 39 0D 0A 43 6F 6F 6B 69 65 3A 20 61 67 68 5F 73 65 73 73 69 6F 6E 3D 32 35 36 31 39 30 37 65 34 36 63 61 61 66 62 63 36 30 66 39 64 61 35 65 61 63 36 31 61 37 64 38 3B 20 6E 64 2D 70 6C 61 79 65 72 2D 36 31 36 34 36 64 36 39 36 65 3D 66 63 35 34 38 66 34 62 2D 61 65 61 66 2D 34 33 66 65 2D 39 30 61 35 2D 38 64 34 34 66 62 65 39 37 61 39 63 3B 20 4C 4F 42 45 5F 4C 4F 43 41 4C 45 3D 7A 68 2D 43 4E 3B 20 63 6C 6F 75 64 72 65 76 65 2D 73 65 73 73 69 6F 6E 3D 4D 54 63 78 4D 6A 55 30 4E 7A 49 32 4E 6E 78 4F 64 33 64 42 54 6B 56 57 57 6C 55 77 4D 55 68 54 4D 55 70 4C 56 32 78 47 55 56 5A 72 56 6C 52 58 52 45 70 57 55 57 74 6F 55 46 4A 46 4D 48 6C 54 56 57 78 51 55 32 73 35 51 6C 52 73 54 6C 46 53 4D 55 4A 54 55 31 52 4B 57 45 35 46 5A 7A 4A 56 56 54 6C 51 54 57 70 61 54 6C 4A 72 4E 48 6C 53 4D 55 55 39 66 43 62 5F 6F 77 75 36 45 47 77 72 72 77 65 6D 4C 66 4D 55 53 65 64 43 46 53 7A 2D 38 6A 77 6F 47 71 70 65 50 46 33 6E 6E 4F 6B 42 0D 0A 0D 0A
stdout: 
stdout:    at MUnique.OpenMU.Network.PacketPipeReaderBase.ReadBufferAsync() in /src/Network/PacketPipeReaderBase.cs:line 93
stdout:    at MUnique.OpenMU.Network.PacketPipeReaderBase.ReadSourceAsync() in /src/Network/PacketPipeReaderBase.cs:line 51
stdout:    at MUnique.OpenMU.Network.PacketPipeReaderBase.ReadSourceAsync() in /src/Network/PacketPipeReaderBase.cs:line 67
stdout:    at MUnique.OpenMU.Network.Connection.BeginReceiveAsync() in /src/Network/Connection.cs:line 105

**Comment by sven-n** [comment]
The logged error is caused by a http client that tries to access the game server. You can put the hex string to an online converter, and see that.

So the question is, what exactly do you do and what do you see?
"The client cannot connect to the server." is pretty vague.

**Comment by 496080199** [comment]
I used vmware to deploy an openwrt virtual machine on a Win11 computer. Openwrt has a docker environment integrated, so openMU was deployed to openwrt through docker-compose. The docker-compose file used is this: https://github.com /MUnique/OpenMU/blob/master/deploy/all-in-one/docker-compose.yml. After successful deployment, set IP Resolving to Custom and Custom IP/Hostname to the IP of the Openwrt router. However, when the client running on the computer connects to OpenMU of Openwrt, it prompts that it cannot connect, so I don’t know how to solve the problem?
Configuration reference document:https://9418666.xyz/archives/2301.html

**Comment by sven-n** [comment]
I read this document (translated). It seems valid, but it's incomplete.
* How do you start your game client?
* Are these errors really occur in the moment you try to connect to the game?

**Comment by 496080199** [comment]
I thought it might be the packet forwarding problem of the openwrt bridged wireless network in vmware of my windows laptop. Later, I directly used an x86 soft routing machine with a wired network card to test. The MU client on the computer can connect to OpenMU on that openwrt machine normally.  Thanks for your help, sorry for the trouble.
