### ISSUE TITLE
excelent job, add season1 ver 1.02i proto koreano 

### ISSUE THREAD

**Issue by agustin9014** [MUnique/OpenMU#413]
excelent job, add season1 ver 1.02i proto koreano ?

**Comment by sven-n** [comment]
Hi Agustin,
unfortunately, I'm not planning to add this version. The only supported version will maybe be 0.97d and then an improved season 6 client, based on the available sources.
However, if someone is motivated to add any other version, I'm open to accept pull requests, of course.
