### ISSUE TITLE
Points per reset can be set by Character Class

### ISSUE THREAD

**Issue by Niter88** [MUnique/OpenMU#416]
I'm adding a new feature to the Reset Plugin that lets the GMs configure a different reset point for each class.

It has to be activated on the plugin in order to take effect, also you have to specify a value upon editing the class. The value of -1 means deactivated and will still use the plugin default value

**Comment by Niter88** [comment]
just leaving a note here, this feature will added up with a custom points number for VIP accounts.
That is, after we make such a feature. This will of course be in another issue.

**Comment by sven-n** [comment]
Can this be closed now?
