### ISSUE TITLE
[Error] Gates issue

### ISSUE THREAD

**Issue by ThisMushroom** [MUnique/OpenMU#42]
### **Steps to reproduce:**

1) Go to the Lorencia -> Devias gate
2) Enter Devias
3) Go back to Lorencia

### **Result:**

**No error occure but server and client stuck.**
Short look: stuck occures at the moment when
```
 public void EnterGate(Player player, EnterGate enterGate){
...
if (player.CurrentMap.Definition.EnterGates.Contains(enterGate) && !(player.X >= enterGate.X1 - INACCURACY &&
                  player.X <= enterGate.X2 + INACCURACY &&
                  player.Y >= enterGate.Y1 - INACCURACY &&
                  player.Y <= enterGate.Y2 + INACCURACY))
            {
                return;
            }
...
}
```
causes _return_. Return triggers in 90% of cases due to small INACCURACY (currently its **2**). _Tested with **4** - everything is fine._

After INACCURACY changed to 4 and it become working next error occured:
```
[ERROR] 2018-07-14 15:18:37,227 [MUnique.OpenMU.GameServer.RemoteView.RemotePlayer] [0] - System.NullReferenceException: Ссылка на объект не указывает на экземпляр объекта.
   в MUnique.OpenMU.GameLogic.Player.WarpTo(ExitGate gate) в D:\MuProject\TheServer\OpenMU-1\src\GameLogic\Player.cs:строка 502
   в MUnique.OpenMU.GameLogic.PlayerActions.WarpGateAction.EnterGate(Player player, EnterGate enterGate) в D:\MuProject\TheServer\OpenMU-1\src\GameLogic\PlayerActions\WarpGateAction.cs:строка 55
   в MUnique.OpenMU.GameServer.MessageHandler.WarpGateHandler.HandlePacket(Player player, Byte[] packet) в D:\MuProject\TheServer\OpenMU-1\src\GameServer\MessageHandler\WarpGateHandler.cs:строка 50
   в MUnique.OpenMU.GameServer.ConfigurablePacketHandler.HandlePacket(Player player, Byte[] packet) в D:\MuProject\TheServer\OpenMU-1\src\GameServer\ConfigurablePacketHandler.cs:строка 56
   в MUnique.OpenMU.GameServer.RemoteView.RemotePlayer.PacketReceived(Byte[] buffer) в D:\MuProject\TheServer\OpenMU-1\src\GameServer\RemoteView\RemotePlayer.cs:строка 71
```

### **Steps to reproduce:**

1) Change INACCURACY  to 4
2) Enter Devias via Lorencia gate
3) Leave Devias -> Enter Lorencia
4) Enter Devias again
5) Try to leave Devias via Lorencia gate

**Upd.**
Error occures at 

```
public void EnterGate(Player player, EnterGate enterGate){
...
player.WarpTo(enterGate.TargetGate);
...
}
```
Because of enterGate.TargetGate == NULL. 
targetGateId is ok but rawTargetGate and targetGate become NULL.

**Comment by sven-n** [comment]
I think the inaccuracy is not the problem... it should probably use the WalkTarget coordinates instead of the current x and y for the comparison.

The empty target gate is probably again a data loading issue at the JsonObjectDeserializer. There is a circular reference which could make problems.

**Comment by ThisMushroom** [comment]
Yeap, with inaccuracy figured it out this morning...
But unlucky me - had not yet looked how JsonObjectDeserializer works
