### ISSUE TITLE
How to update the game version?

### ISSUE THREAD

**Issue by sd3420625** [MUnique/OpenMU#436]
Hello everyone, I installed the game server through docker and ran it for a week, and I have created character data. 

Today I found that after the git repository was updated, the library file was updated in the local git folder. I would like to ask you how to update the game without changing the character database, and what command can be used to achieve this? Is it enough to stop docker and run the game configuration startup command again?

**Comment by sven-n** [comment]
```
# Pull all images in the stack
docker-compose pull

# Restart the stack
# If a new image version has been pulled, containers 
# using the old tag will be replaced with new instances.
docker-compose up -d
```
See: https://www.howtogeek.com/devops/how-to-upgrade-docker-containers-to-apply-image-updates/

The database is usually not stored inside a docker container, but a volume. So if you replace a container, your data should still be there.
However, I highly recommend doing a backup of the database before doing any update.
