### ISSUE TITLE
A bug appeared after equipping the third generation wings

### ISSUE THREAD

**Issue by sd3420625** [MUnique/OpenMU#457]
**Describe the bug**
After equipping three generations of wings (including wing of ruin and wing of eternal), you will occasionally receive a huge amount of damage during the fight against monsters (the amount of damage shown in red is 65535), causing the character to die instantly. The status of the wings is regular attributes + 9 levels with increased luck and additional attack power, excluding other attributes.

**Expected behavior**
1.Fix this bug to avoid abnormal damage figures
2.Is it possible to change the conditions for synthesizing the third-generation wings to a configurable item, especially since the Feather of Condor disappears after the second phase of synthesis fails? After all, this item is very difficult to synthesize in the first phase.

**Comment by sven-n** [comment]
1. I'm working on it at PR #456 
2. All of that is not hard coded, it can be changed in the configuration at Monsters -> Chaos Goblin -> Item Craftings -> 3rd Level Wings, Stage 1/2. However, it was meant to be that hard by webzen ;)

**Comment by sd3420625** [comment]
> 1. I'm working on it at PR [Fix damage absorb/increase item options #456](https://github.com/MUnique/OpenMU/pull/456)
> 2. All of that is not hard coded, it can be changed in the configuration at Monsters -> Chaos Goblin -> Item Craftings -> 3rd Level Wings, Stage 1/2. However, it was meant to be that hard by webzen ;)

Great! This is really good news. Thx a lot~
