### ISSUE TITLE
Questions about seed synthesis

### ISSUE THREAD

**Issue by sd3420625** [MUnique/OpenMU#459]
**Describe the bug**
Due to the unfixed prerequisites, I set the Jewel of Harmony to drop directly. Now a bug occurs when synthesizing seeds. After clicking the synthesis button, all items do not change or disappear, and no seeds are generated. I have queried There is no problem with the synthesis formula of Seed Master in the website data. 
I would like to ask if the entire Seed Sphere synthesis system has not been repaired?

**Expected behavior**
Looking forward to fixing the following crafting systems:
Jewel of Harmony -> Seed -> Seed Sphere -> Inlay gems into equipment
Btw, the Gemstone refining system can be slowed down without any rush :)

**Comment by sven-n** [comment]
It's a small error in the configuration. The server is configured to require a blue option (from jewel of life) on the excellent and ancient items. However, the client doesn't require that these items have that option. I'll fix that soon 😅
