### ISSUE TITLE
Jewel of Bless & Soul from merchant are bugged

### ISSUE THREAD

**Issue by UE4SS** [MUnique/OpenMU#465]
**Describe the bug**
It's possible to dupe jewels purchased from a merchant.
This doesn't happen if the jewel has dropped from a monster.

**To Reproduce**
1. Add Jewel of Bless to a merchant.
2. Purchase a Jewel of Bless.
3. Apply the jewel to an item.
4. Exit to the character selection screen, or server selection screen.
5. Log back in, and you should have +1 on your item and also still have the jewel.

**Expected behavior**
The jewel should be consumed.

**Screenshots**
![mu-online-jewel-dupe.webm](https://github.com/user-attachments/assets/77ffa1be-e9b6-42e4-8e20-3971d6e6b64c)

**Desktop (please complete the following information):**
OS: Linux Mint Cinnamon

**Comment by sven-n** [comment]
Fixed with [5fad28a](https://github.com/MUnique/OpenMU/commit/5fad28acd06adbc01d98925f4660dcb2c62086e0)
