### ISSUE TITLE
Implement Launcher with auto-update feature

### ISSUE THREAD

**Issue by sven-n** [MUnique/OpenMU#5]
There is already a client launcher project which is pretty basic.
It's missing a dialog to configure the game client (resultion, sound etc.) and the auto-update feature.

We could implement auto-update compatible to the original launcher, and/or make our own (e.g. with torrents).

**Comment by Apollyon221** [comment]
I would like to do this, i was thinking on using WPF and to move all the current ClientLauncher to this and the configuration to here, but i will need some more of your opinions, maybe a sketch on how it should like.

Maybe we can use Mahapps + MaterialDesign, What do you think?

**Comment by sven-n** [comment]
Is Metro still a thing in 2019? :D

Well, I’m fine with any UI technology or style as long as the actual logic is independent from it.
Would be great if the style or images could be configurable.

**Comment by Apollyon221** [comment]
Dunno just was suggesting something,yep with MVVM we can do that, all the logic is outside the UI and we can have multiple UIs using the same logic, will start working on it when i have the time then

**Comment by Mosch0512** [comment]
I would be interested in doing that too. I would use Java or Kotlin for the job and JavaFx or TornadoFx as GUI frameworks.

**Comment by sven-n** [comment]
Thanks for your interest, but honestly I would rather keep it in C# than introducing another language and more frameworks to this project.

**Comment by Mosch0512** [comment]
I am fine with that too :) I think there is no launcher included right now right?

**Comment by sven-n** [comment]
There is, but just a very basic one:
https://github.com/MUnique/OpenMU/tree/master/src/ClientLauncher

**Comment by sven-n** [comment]
I'd like to close this issue for now. One reason is, that I'd like to keep the scope of the project a bit narrower. It never had a high priority for me and a good launcher can be a big project on its own and doesn't have to be bound to OpenMU or MU Online in general.

If you still want to develop a launcher for OpenMU, feel free to move your code to a separate repository. However, if you need assist or are missing APIs in OpenMU, feel free to open a new issue.
