### ISSUE TITLE
Duel System Bug

### ISSUE THREAD

**Issue by nitoygo** [MUnique/OpenMU#507]
**Describe the bug**
Duel does not proceed after round 1 (first kill)

**To Reproduce**
1. Player1 -> Player2: Request Duel
2. Player2 -> Player2: Accept Invite
3. Player1 -> Player2: Attack until killed (once)
4. // wait for next round
5. // Can no longer attack to continue next round

**Expected behavior**
After each round, both Player1 and Player2 should still be able to attack each other

**Screenshots**
In this screenshot, it's already round 2, but cursor is already in non-attack mode
![image](https://github.com/user-attachments/assets/7c901ac6-f369-42cf-aa98-8c451e844aa1)

**Additional bugs**
** A duelist can switch char and still be in the duel room after reconnecting
** When one duelist, changes maps, the other one is left in the duel room (should be warped out)

**Comment by sven-n** [comment]
Will be fixed... I'm working on that on branch dev/duel-fixes
