### ISSUE TITLE
Repair Not Working on Gywen Pendant of Ability

### ISSUE THREAD

**Issue by nitoygo** [MUnique/OpenMU#508]
**Describe the bug**
Repairing Gywen Pendant of Ability does not work

**To Reproduce**
1. Login using 'ancient' and select 'ancientElf'
2. Inspect pendant (initial durability of Gywen Pendant is 50/70)
3. Click Repair Icon (Hammer) and apply action to the pendant
4. Gywen Pendant remains damaged (no effect)

**Expected behavior**
Gywen Pendant should be 70/70 after repair

**Screenshots**
![image](https://github.com/user-attachments/assets/2240f40d-2a9b-462c-995c-973b64226f79)

**Additional context**
* Tried on Broy's Pendant: OK
* Tried on Vicious Ring: OK

**Comment by sven-n** [comment]
Gywen Pendant is somehow special, because it is ancient, but has no ancient bonus option. However, the ItemExtensions.IsAncient() is checking the bonus :-/

**Comment by sven-n** [comment]
Current:
```csharp
    public static bool IsAncient(this Item item)
    {
        return item.ItemOptions.Any(link => link.ItemOption?.OptionType == ItemOptionTypes.AncientBonus);
    }
```

Fix:
```
    public static bool IsAncient(this Item item)
    {
        return item.ItemSetGroups.Any(itemSet => itemSet.AncientSetDiscriminator > 0);
    }
```

You can create a PR if you want. I'll try to fix this as soon as I can

**Comment by nitoygo** [comment]
How about making our own business rule that gywen will have a bonus? 😂
