### ISSUE TITLE
Appearance Serializer for character does not include ancient options

### ISSUE THREAD

**Issue by nitoygo** [MUnique/OpenMU#511]
**Describe the bug**
Appearance Serializer for own character and other players in scope does not include ancient items

**To Reproduce**
1. Login 'ancient'
2. Select any character
3. Check character appearance
4. // Notice that the armor does not have ancient set aura
5. Switch/reload character
6. // Notice that the armor now show ancient set aura

**Expected behavior**
Ancient set aura should be shown always if complete

**Additional context**
* This also happen for new characters entering your scope of vicinity that has ancient sets equipped
* From initial investigation, newPlayer.AppearanceData.EquippedItems does not have any ancient option included (data fetch issue?)

**Comment by sven-n** [comment]
Thanks for pointing that out - I wasn't aware of this issue 🙈

**Comment by nitoygo** [comment]
Sure thing. I'm just familiarizing myself with the source code :D
Is it somewhere related to here?
![image](https://github.com/user-attachments/assets/91c5eb36-48d4-4df0-bd31-3fc650ea92db)
