### ISSUE TITLE
Elf: Can't re-equip Gywen Bow

### ISSUE THREAD

**Issue by nitoygo** [MUnique/OpenMU#517]
**Describe the bug**
After removing the Gywen Bow, I can't equip it again

**To Reproduce**
1. Login Ancient, select ancientElf
2. Unequip Gywen Bow
3. Try to re-equip Gywen Bow
4. // unable to equip....

**Expected behavior**
Should be able to re-equip Gywen Bow

**Screenshots**
![image](https://github.com/user-attachments/assets/fe6c4a9d-6993-4eb8-b54c-d7ddb75cf185)

**Comment by sven-n** [comment]
OpenMU has the wrong requirement values for some items. It has the requirements for a level 0 item in the item definition, but the actual value is calculated by an abstract value which doesn't have anything to do with the visible value.
You can see the calculation at `ItemExtensions.CalculateRequrement(this Item item...`.
This code calculates a requirement of 725 Agility and 298 Strength, but it must be 380 Agility and 148 Strength.

I checked some config data:
* OpenMU ItemDefinition: 70 Strength, 188 Agility
* Server files Item.txt: 30 Strength, 100 Agility

So, to fix this, the data needs to be checked... e.g. by extracting the correct values from some other season 6 server files and comparing them to the ones in the database. I'll write some code to do that when I have some time.
