### ISSUE TITLE
MU Helper Config Not Received on Character Login

### ISSUE THREAD

**Issue by nitoygo** [MUnique/OpenMU#528]
**Describe the bug**
MU Helper Config Not Received on Character Login

**To Reproduce**
0. Run debug mode
1. Login character
2. Check debug logs
3. No MU Helper packet received

**Expected behavior**
MU Helper packet 0xAE should be logged

**Additional context**
https://github.com/MUnique/OpenMU/blob/master/docs/Packets/C2-AE-MuHelperConfigurationData_by-server.md

**Comment by sven-n** [comment]
It's only sent when there is saved data for this character, see `Player.OnPlayerEnteredWorldAsync`.
Can you reproduce the issue with a character which has a saved configuration with the season 6 client?

**Comment by nitoygo** [comment]
I see. That could be the case. I'll save the config from S6 client, then login the same character in MuMain and see if i get the packets.

**Comment by nitoygo** [comment]
Confirmed. Sorry, closing ticket.

**Comment by nitoygo** [comment]
Question, should we just save a zero'd out data for each characters by default and just send it out to the client as if there is data saved?

**Comment by sven-n** [comment]
Saving zeroed data makes no sense to me, as it just wastes disk space. Same for sending that over the wire. The client should initialize an empty config when it selects a character. So when the server sends a config, the client can take that.
