### ISSUE TITLE
[OSX, VS4MAC] Admin panel not working

### ISSUE THREAD

**Issue by afrokick** [MUnique/OpenMU#53]
Hi
 
I had an issue with admin panel.

When I open a tab with localhost:1234/admin, some errors occurred in console:

`
GET http://localhost:1234/content/js/app.js 404 (Not Found)
admin:14 
GET http://localhost:1234/content/css/app.css 404 (Not Found)`

How can I run minifier that creates app.js and app.css?

VS2017, OSX 10.13.6

**Comment by sven-n** [comment]
Hello,

the TypeScript compiler creates the app.js, so it doesn't seem to run. Unfortunately, as far as I know, Visual Studio for Mac is not the same as for Windows. It's more like Visual Studio Code. Therefore, I don't know if it runs the TypeScript compiler. The TypeScript compiler is usually restored within the nuget packages, e.g. the project file defines this here:
```
  <Target Name="EnsureNuGetPackageBuildImports" BeforeTargets="PrepareForBuild">
    <PropertyGroup>
      <ErrorText>This project references NuGet package(s) that are missing on this computer. Use NuGet Package Restore to download them.  For more information, see http://go.microsoft.com/fwlink/?LinkID=322105. The missing file is {0}.</ErrorText>
    </PropertyGroup>
    <Error Condition="!Exists('..\packages\BuildBundlerMinifier.2.7.385\build\BuildBundlerMinifier.targets')" Text="$([System.String]::Format('$(ErrorText)', '..\packages\BuildBundlerMinifier.2.7.385\build\BuildBundlerMinifier.targets'))" />
    <Error Condition="!Exists('..\packages\Microsoft.TypeScript.MSBuild.2.8.3\build\Microsoft.TypeScript.MSBuild.props')" Text="$([System.String]::Format('$(ErrorText)', '..\packages\Microsoft.TypeScript.MSBuild.2.8.3\build\Microsoft.TypeScript.MSBuild.props'))" />
    <Error Condition="!Exists('..\packages\Microsoft.TypeScript.MSBuild.2.8.3\build\Microsoft.TypeScript.MSBuild.targets')" Text="$([System.String]::Format('$(ErrorText)', '..\packages\Microsoft.TypeScript.MSBuild.2.8.3\build\Microsoft.TypeScript.MSBuild.targets'))" />
  </Target>
  <Import Project="..\packages\Microsoft.TypeScript.MSBuild.2.8.3\build\Microsoft.TypeScript.MSBuild.targets" Condition="Exists('..\packages\Microsoft.TypeScript.MSBuild.2.8.3\build\Microsoft.TypeScript.MSBuild.targets')" />
```

Did you try with Debug or Release build?
You can ignore the app.css error as it's not really used anymore - I'll remove it from the page.

**Comment by sven-n** [comment]
This guide might be helpful: https://www.michaelcrump.net/using-typescript-with-code/

**Comment by afrokick** [comment]
The issue disappeared after update to the last version of VS4Mac.

As I understood, It was an error in the project file, which prevents copy files to content/js content/css folders.

Thanks for help)
