### ISSUE TITLE
Chaos Machine Item Recovery

### ISSUE THREAD

**Issue by nitoygo** [MUnique/OpenMU#534]
**Describe the bug**
Items left in chaos machine can not be recovered when game crashes or on disconnection

**To Reproduce**
1. Place items for chaos mixing
2. // Disconnect or crash happens
3. Reconnect 
4. // Items are lost

**Expected behavior**
Server has a way or an option for the player to recover items left unintentionally in the chaos machine

**Comment by sven-n** [comment]
I think the best would be to handle this like the trade. When a disconnect happens, the items should be moved back to the original position before saving the account.

**Comment by nitoygo** [comment]
Agreed. However, for the case where the mix already happened, it might need special handling (?). No idea yet what happens to the persistence of that new/upgraded item.

**Comment by sven-n** [comment]
Yea, that needs some extra logic for sure
