### ISSUE TITLE
Attacking a party member is currently allowed

### ISSUE THREAD

**Issue by nitoygo** [MUnique/OpenMU#545]
**Describe the bug**
A player can attack a party member

**To Reproduce**
1. Login 2 or more characters
2. Create party
3. Attack one of your party members (ctrl + right/left click)
4. // Damage dealt

**Expected behavior**
It should be prohibited to attack your party mates

**Comment by sven-n** [comment]
I don't remember that party members can't attack each other 😉
In the old days, we used to party each other for duels, so that we saw that nobody used potions.

**Comment by nitoygo** [comment]
I see. Non-issue then xD closing...
