### ISSUE TITLE
Isn't the teleport skill delay too long?

### ISSUE THREAD

**Issue by nitoygo** [MUnique/OpenMU#549]
This is probably 'standard' (same behavior as GMO)
![image](https://github.com/user-attachments/assets/21972d0d-0c56-4a8e-8fd7-c62871621041)
but, I think 1500ms delay before teleporting seems too slow for a 'teleport'.

Could we make this shorter? like 300ms or 500ms? or configurable

**Comment by sven-n** [comment]
As far as I remember I tried to implement it as original as possible. Reducing this time also gives an advantage in PvP for the wizards. Best would be a configuration for that, I guess. I'm not sure where it fits the best yet. Maybe a plugin configuration? 😅

**Comment by nitoygo** [comment]
To balance this advantage, we could make it similar to summon that has a cooldown. 😂 but yeah, understandable if we're really copying the original behavior.
