### ISSUE TITLE
Admin panel not working on Windows

### ISSUE THREAD

**Issue by tehKaiN** [MUnique/OpenMU#55]
So I've just installed VS2017 with .net worload. Server starts (I guess, everything's green in console), but I've got blank page and errors in web console:

```
Loading failed for the <script> with source “http://localhost:1234/content/js/app.js”. admin:13
Loading failed for the <script> with source “http://localhost:1234/components/App”. admin:1
Error: "Fetching http://localhost:1234/components/App
  Instantiating http://localhost:1234/components/App
  Loading components/App"
ahttp://localhost:1234/content/js/system-production.js:4:11962
```
There was a problem earlier with unhanled exception which I fixed by typing command left in comment in elevated command prompt: `netsh http add urlacl http://+:1234/ user=[Username]` where username I've wrote my OS user name.

I've tried to install "JavaScript & TypeScript Language Support" package but no luck.

Using latest VS2017 Community, Win10 Enterprise

**Comment by sven-n** [comment]
Hi, it seems like the TypeScript build doesn't run. As far as I can tell by looking at my own VS installations, you need the following Visual Studio extensions:
  * TypeScript Build for Microsoft Visual Studio
  * TypeScript for Microsoft Visual Studio

If it works for you, I'll add it as requirement in the quick start guide.

It also doesn't hurt to have the newest VS update, I guess. I'm currently running versions 15.3.4 and 15.7.1 on my machines.

**Comment by sven-n** [comment]
Sure, if it's not too much work and helpful for others ;-)

**Comment by sven-n** [comment]
I think I know what's the only requirement to build the Typescript stuff: The Typescript SDK ;)
That's what I had to install after an update to 3.0.

**Comment by Alex-G** [comment]
if I create a new user through the Admin panel, the password field is empty in the database

**Comment by sven-n** [comment]
Oh, yes that's a bug... the AdminPanel (typescript code) transmits the property as "Password", but the AccountModule has it defined in AccountDto as "NewPassword".
Thanks for reporting, I'll fix it soon ;)

**Comment by sven-n** [comment]
I guess we can close this issue now ;)
