### ISSUE TITLE
[Features] Deserializator for each serializator

### ISSUE THREAD

**Issue by afrokick** [MUnique/OpenMU#59]
It would be perfect to have deserializator for any serializator. F.e. inventory, character's items.

**Comment by sven-n** [comment]
Do you mean, you need deserializers for all packet types which are implemented yet?
I mean Inventory/Items and Appearance are the hardest ones - I can help and create something. The rest is pretty trivial, but a lot of work :-/

**Comment by sven-n** [comment]
I made some progress with the deserializing function for the ItemSerializer.
Unfortunately, I found a problem again. MU Online has up to two different ancient sets per item. Currently the ItemSetGroup can’t tell us to which one it belongs. Not a big problem, but this will require a data model extension - and I’m not sure yet how to add it.

**Comment by sven-n** [comment]
Committed my current state. The issue with ancient sets is still not completely solved, though.
Also need some more unit tests.

**Comment by sven-n** [comment]
The ItemSerializer should work now, but unit tests have to be extended, too.
