### ISSUE TITLE
Log possible hacker actions, remove TODO comments

### ISSUE THREAD

**Issue by sven-n** [MUnique/OpenMU#77]
We want to log suspicious player activity to catch potential hackers. At some places in the code we already log these activities, at some other places we placed TODO comments. It would be nice to add logging where we currently only have TODOs. For example [here](https://github.com/MUnique/OpenMU/blob/953eb74f1ee52bedf210fab4ecabc32b48d36d39/src/GameLogic/PlayerActions/Guild/GuildRequestAnswerAction.cs#L48) and [here](https://github.com/MUnique/OpenMU/blob/953eb74f1ee52bedf210fab4ecabc32b48d36d39/src/GameLogic/PlayerActions/Items/SimpleItemCraftingHandler.cs#L50).

Nice to have, but requires knowledge of the game and its mechanics: Identify more places where a player tries to do something when it's actually not possible when using an unmodified game client.

**Comment by wojciech-dabrowski** [comment]
Done
