### ISSUE TITLE
Solution Organization

### ISSUE THREAD

**Issue by Apollyon221** [MUnique/OpenMU#92]
Hey i am new to this project, so i wanted to help out, started reading the code and while i was doing that i saw what a mess the solution is(at least for me), "*.Tests" projects together with normal projects and etc.

I will be starting a fork today and do some heavy modifications to the Solution and projects organization, i dont know if you will like it, but if in any case you do i will do a pull request if not i will have to develop in my fork you are free to copy and paste my code.

And a question would you mind if i started a new repo and reworkd the project in my way and continued the development there?

Sorry if i was rude, if i was i didnt mean to, my english is not that good so sometimes i might seem rude and that is not what i intended, i really liked the project and wanted to get into it, i just dislike its organization.

**Comment by sven-n** [comment]
Hello,
the solution structure is as it was intended by me.

Why would you remove the *.Tests from the solution? If you refactor your code (Renaming things, for example), the tests are updated almost automatically. If you remove them from the solution, they are not. Also, you can let them run all the time during development...

I can’t tell you if I would merge your changes as I don’t clearly see what’s your plan ;)

**Comment by Apollyon221** [comment]
I dont mean to remove them, i mean to organize them in folders so it would look like something like this

[https://i.imgur.com/v7geasT.png](Image)

This way it is more friendly for other devs to read and know the project much faster, as it will be more organized.

Another critic from me, it seems like you are splitting projects just for the sake of splitting, an example MUnique.OpenMU.ChatServer and MUnique.OpenMU.ChatServer.ExDbConnector could be on the same project that way it would be way more easier to find what you need and more organized, i am just trying to help my english is not that good sometimes my words doesnt mean what i want they to mean.

Do you have discord or something similar so we could talk more easily?

**Comment by sven-n** [comment]
If this structure of your Screenshot doesn’t require changes in the actual folder structure, I think it’s fine.

And about the ChatServer and ExDbConnector: The ExDbConnector is a side product, which is a replacement for the original ChatServer.exe. That means, it’s not used by the rest of the project. It’s also built for .net core and framework 4.6.1, while ChatServer is built for .net standard.

The only project which is currently so small that it probably doesn’t need a separate project is the LoginServer.

I don’t have Discord, just Gitter and Skype. However, I’m not much more “responsive” there as in the issues ;)

**Comment by sven-n** [comment]
I added a folder structure to the solution (master branch). What do you think about it?

**Comment by sven-n** [comment]
Closed since no further feedback came back.
