### ISSUE TITLE
ClientLauncher can't work

### ISSUE THREAD

**Issue by najoast** [MUnique/OpenMU#96]
I downloaded 1.04d English client, then use the `ClientLauncher` start main.exe, use 127.0.0.1:44405, but nothing happened, `HandleNewSocket()` not be called.

**Comment by sven-n** [comment]
Hello, can you try it with 127.127.127.127 ?
The game client isn’t connecting to 127.0.0.1, I think Webzen prevents this.

**Comment by najoast** [comment]
It works! thank you @sven-n !

Another question, how can I register account? I'm not use PostgreSQL, just run use `-demo`, so I can't insert account into the database.

**Comment by sven-n** [comment]
There are a few test accounts: test0 to test9 and test300 and test400

**Comment by sven-n** [comment]
Ah, and of course you can add more accounts over the admin panel ( http://localhost:1234/admin/ ), but they’re only available until the server process shuts down ;)

**Comment by najoast** [comment]
I successfully entered the game, thank you again, the password of the test account is the same as the account.
