### ISSUE TITLE
Warehouse lock/unlock needs wz password

### ISSUE THREAD

**Issue by najoast** [MUnique/OpenMU#97]
I tried to help you implement this feature, but need a wz password, how to skip it?
Maybe this needs to crack client...

**Comment by sven-n** [comment]
Thanks, but what’s the sense of locking the vault, when unlocking is possible without asking for some kind of a password? ;)

**Comment by zhouyanlt** [comment]
Sorry I didn't describe it clearly. I mean, after entering the warehouse password twice, I also asked for the password for webzen.com.
There are pictures in this [post](http://forum.ragezone.com/f193/remove-webzen-com-password-vault-1147619).

**Comment by najoast** [comment]
Sorry I didn't describe it clearly. I mean, after entering the warehouse password twice, I also asked for the password for webzen.com.
There are pictures in this [post](http://forum.ragezone.com/f193/remove-webzen-com-password-vault-1147619).

**Comment by sven-n** [comment]
Hm, that’s strange. I think you should just need to enter the password if you set or remove the vault password/pin.
If you need it to unlock it, then it’s probably an issue in the client itself.
